---
title: "8.1.K562_external_validation"
output: html_document
date: "2024-06-07"
---

Evaluation of divergent loci using fine-mapped GWAS variants, fine-mapped eQTLs, and CRISPRi data and comparison to other methods & assays.

```{r}

library(CAGEfightR)
library(GenomicRanges)
library(readr)
library(rtracklayer)
library(parallel)
library(ggplot2)
library(GenomicFeatures)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(SummarizedExperiment)
library(tibble)
library(ggrepel)

theme_set(theme_bw(base_size = 10))

```


```{r}

pooled.focus.samples <- c("K562_C","K562_N")
pooled.assay.names <- c("K562_C" = "CAGE divergent loci cells",
                        "K562_N" = "CAGE divergent loci nuclei")
pooled.DL.file <- "../3.DivergentLoci/poolSub.k562.summitDLs.rmSingletons.rds"
pooled.noise.file <- "../9.Noise/K562.poolSub.divnoise.csv"

focus.samples = c("K562_C1","K562_C2","K562_C3","K562_N4","K562_N5","K562_N6")
assay.names = c("K562_C1" = "CAGE divergent loci cells", 
                "K562_C2" = "CAGE divergent loci cells", 
                "K562_C3" = "CAGE divergent loci cells",
                "K562_N4" = "CAGE divergent loci nuclei", 
                "K562_N5" = "CAGE divergent loci nuclei", 
                "K562_N6" = "CAGE divergent loci nuclei")
DL.file = "../3.DivergentLoci/repSub.k562.summitDLs.rmSingletons.rds"

resize.width <- 200

SNP.file <- "../0.External_resources/all.bg.SNPs.hg38.baseline.v1.1.bed.sorted"
eQTL.file <- "../0.External_resources/GTEx_30tissues_release1_pip_01_Whole_Blood.tsv"
GWAS.file <- "../0.External_resources/UKBB_94traits_release1_pip02_clean_hg38.bed"

eQTL.pip.thres <- 0.5
GWAS.pip.thres <- 0.2
traits <- c("Plt","HbA1c","Hb","RBC","MCV","MCH","MCHC")

cCRE.file <- "../0.External_resources/ENCFF464BRU.bed"

PINTS.files <- c("PINTS GRO/PRO-cap distal" = "../0.External_resources/K562_Distal_PINTS_GRO_PRO_cap.bed",
                 "PINTS GRO/PRO-cap proximal" = "../0.External_resources/K562_Proximal_PINTS_GRO_PRO_cap.bed")

dREG.files <- c("dREG PRO-seq" = "../0.External_resources/GSE150625_PROseq_1M_K562_dREGpeaks_clean.bed",
                "dREG qPRO-seq" = "../0.External_resources/GSE150625_qPROseq_1M_K562_dREGpeaks_clean.bed")

FANTOM5.file <- "../0.External_resources/F5.hg38.enhancers.expression.matrix.gz"
FANTOM5.enhancers.file <- "../0.External_resources/F5.hg38.enhancers.bed.gz"
FANTOM5.id <- "CNhs12334"

CRISPR.pos.file <- "../5.EPCrisprBenchmark/1.EPC.pos.gr.rds"
CRISPR.neg.file <- "../5.EPCrisprBenchmark/1.EPC.neg.notsig.gr.rds"

preds.thres <- 0.2
preds.genome.files <- paste("../8.Genomewide_prediction/pred_all_repSub_tcs_",focus.samples,".bed",sep="")
names(preds.genome.files) <- focus.samples
preds.genome.names <- c("K562_C1" = "CAGE predictions cells replicates",
                        "K562_C2" = "CAGE predictions cells replicates",
                        "K562_C3" = "CAGE predictions cells replicates",
                        "K562_N4" = "CAGE predictions nuclei replicates",
                        "K562_N5" = "CAGE predictions nuclei replicates",
                        "K562_N6" = "CAGE predictions nuclei replicates")

pooled.preds.genome.files <- paste("../8.Genomewide_prediction/pred_all_poolSub_tcs_",pooled.focus.samples,".bed",sep="")
names(pooled.preds.genome.files) <- pooled.focus.samples
pooled.preds.genome.names <- c("K562_C" = "CAGE predictions cells pooled",
                               "K562_N" = "CAGE predictions nuclei pooled")

```


Read in data

```{r}

txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
cds <- unlist(cdsBy(txdb,"gene"))
promoters <- promoters(txdb,upstream=500,downstream=500)

## Background SNPs
SNP.data <- import.bed(SNP.file)
SNP.data <- sort(SNP.data)
olap <- findOverlaps(SNP.data,cds,minoverlap=1)
SNP.data <- SNP.data[-queryHits(olap)]

## CAGE predictions
preds <- lapply(names(preds.genome.files), function(n) {
  gr <- read_tsv(preds.genome.files[n],show_col_types = FALSE)
  score <- gr$score
  gr <- makeGRangesFromDataFrame(gr[,1:3])
  gr$score <- score
  seqlevels(gr,pruning.mode="coarse") <- seqlevels(SNP.data)
  gr <- resize(gr, width=resize.width, fix="center")
  pc <- rep("distal",length(gr))
  olap <- findOverlaps(gr,promoters,minoverlap = 1)
  pc[queryHits(olap)] <- "proximal"
  gr$class <- pc
  gr
})
names(preds) <- names(preds.genome.files)

## CAGE predictions from pooled samples
pooled.preds <- lapply(names(pooled.preds.genome.files), function(n) {
  gr <- read_tsv(pooled.preds.genome.files[n],show_col_types = FALSE)
  score <- gr$score
  gr <- makeGRangesFromDataFrame(gr[,1:3])
  gr$score <- score
  seqlevels(gr,pruning.mode="coarse") <- seqlevels(SNP.data)
  gr <- resize(gr, width=resize.width, fix="center")
  pc <- rep("distal",length(gr))
  olap <- findOverlaps(gr,promoters,minoverlap = 1)
  pc[queryHits(olap)] <- "proximal"
  gr$class <- pc
  gr
})
names(pooled.preds) <- names(pooled.preds.genome.files)

## Divergent loci from replicate samples
DLs <- readRDS(DL.file)
if (is.list(DLs))
  DLs <- do.call("c",DLs)
seqlevels(DLs, pruning.mode="coarse") <- seqlevels(SNP.data)
DLs <- DLs[DLs$sample %in% focus.samples]
DLs <- resize(DLs, width=resize.width, fix="center")
dlc <- rep("distal",length(DLs))
olap <- findOverlaps(DLs,promoters,minoverlap = 1)
dlc[queryHits(olap)] <- "proximal"
DLs$class <- dlc

## Divergent loci from pooled samples
pooled.DLs <- readRDS(pooled.DL.file)
if (is.list(pooled.DLs))
  pooled.DLs <- do.call("c",pooled.DLs)
seqlevels(pooled.DLs, pruning.mode="coarse") <- seqlevels(SNP.data)
pooled.DLs <- pooled.DLs[pooled.DLs$sample %in% pooled.focus.samples]
pooled.DLs <- resize(pooled.DLs, width=resize.width, fix="center")

dlc <- rep("distal",length(pooled.DLs))
olap <- findOverlaps(pooled.DLs,promoters,minoverlap = 1)
dlc[queryHits(olap)] <- "proximal"
pooled.DLs$class <- dlc

## noise estimates
pooled.noise.thresholds <- read_csv(pooled.noise.file,col_names=TRUE,show_col_types=FALSE)
pooled.noise.thresholds <- pooled.noise.thresholds[pooled.noise.thresholds[,1]=="95%",pooled.focus.samples]

## eQTL data
eQTL.data <- read_tsv(eQTL.file,col_names=FALSE,show_col_types=FALSE)[,c(1,3)]
colnames(eQTL.data) <- c("variant","pip")
pos <- as.numeric(sapply(eQTL.data$variant, function(n) strsplit(n,"_")[[1]][2]))+1
eQTL.data <- GRanges(seqnames=as.character(sapply(eQTL.data$variant, function(n) strsplit(n,"_")[[1]][1])),
                     score=eQTL.data$pip,
                     ranges=IRanges(pos, pos))
eQTL.data <- sort(eQTL.data)
seqlevels(eQTL.data,pruning.mode="coarse") <- seqlevels(SNP.data)
eQTL.data <- subset(eQTL.data, score >= eQTL.pip.thres)
eQTL.data <- reduce(eQTL.data,min.gapwidth=0)
olap <- findOverlaps(eQTL.data,cds,minoverlap=1)
eQTL.data <- eQTL.data[-queryHits(olap)]

eQTL.n <- length(eQTL.data)

## GWAS data
GWAS.data <- import.bed(GWAS.file)
seqlevels(GWAS.data,pruning.mode="coarse") <- seqlevels(SNP.data)
olap <- findOverlaps(GWAS.data,cds,minoverlap=1)
GWAS.data <- GWAS.data[-queryHits(olap)]
GWAS.data <- subset(GWAS.data, name %in% traits)

trait.count.df <- do.call("rbind", lapply(traits, function(trait) {
  dat <- subset(GWAS.data, name==trait)
  dat <- sort(dat)
  dat <- unique(dat)
  as.data.frame(table(dat$name))
}))

trait.count.df

GWAS.data <- sort(GWAS.data)
GWAS.data$score <- NULL
GWAS.data$name <- NULL
GWAS.data <- unique(GWAS.data)

GWAS.n <- length(GWAS.data)

## Point estimate data

point.data <- lapply(names(PINTS.files), function(n) import.bed(PINTS.files[[n]]))
names(point.data) <- names(PINTS.files)
point.data[["PINTS GRO/PRO-cap"]] <- c(point.data[[1]],point.data[[2]])

for (n in names(dREG.files)) {
  gr <- import.bed(dREG.files[n])
  seqlevels(gr,pruning.mode="coarse") <- seqlevels(SNP.data)
  olap <- findOverlaps(gr, promoters, minoverlap = 1)
  gr.proximal <- gr[unique(queryHits(olap))]
  gr.distal <- gr[setdiff(1:length(gr), queryHits(olap))]
  point.data[[n]] <- gr
  point.data[[paste0(n," distal")]] <- gr.distal
  point.data[[paste0(n," proximal")]] <- gr.proximal
}

for (n in names(pooled.preds.genome.files)) {
  gr <- read_tsv(pooled.preds.genome.files[n],show_col_types = FALSE)
  gr <- subset(gr,score>=preds.thres)
  gr <- makeGRangesFromDataFrame(gr[,1:3])
  seqlevels(gr,pruning.mode="coarse") <- seqlevels(SNP.data)
  olap <- findOverlaps(gr, promoters, minoverlap = 1)
  gr.proximal <- gr[unique(queryHits(olap))]
  gr.distal <- gr[setdiff(1:length(gr), queryHits(olap))]
  point.data[[pooled.preds.genome.names[n]]] <- gr
  point.data[[paste0(pooled.preds.genome.names[n]," distal")]] <- gr.distal
  point.data[[paste0(pooled.preds.genome.names[n]," proximal")]] <- gr.proximal
}

cCRE <- read_tsv(cCRE.file,col_names=FALSE,show_col_types=FALSE)
df <- cCRE[,1:3]
colnames(df) <- c("chrom","start","end")
cCRE.data <- makeGRangesFromDataFrame(df)
cCRE.data$class = cCRE[,10,drop=TRUE]

for (n in c("dELS","PLS")) {
 x <- subset(cCRE.data,class==n)
 x$class <- NULL
 point.data[[paste0("ENCODE cCRE ",n)]] <- x
}
point.data[["ENCODE cCRE"]] <- c(point.data[["ENCODE cCRE dELS"]],point.data[["ENCODE cCRE PLS"]])

header <- colnames(read_tsv(FANTOM5.file,n_max=1,show_col_types=FALSE))
FANTOM5.data <- read_tsv(FANTOM5.file,skip=1,col_names=FALSE,show_col_types=FALSE)[,c(1,match(FANTOM5.id,header)+1)]
FANTOM5.enhancers <- flank(swapRanges(import.bed(FANTOM5.enhancers.file)),200,both=TRUE)
FANTOM5.enhancers <- FANTOM5.enhancers[FANTOM5.enhancers$name %in% deframe(FANTOM5.data[FANTOM5.data[2]>0,1])]
point.data[["FANTOM5 enhancers"]] <- FANTOM5.enhancers

for (sample in pooled.focus.samples) {
  gr <- pooled.DLs[pooled.DLs$sample==sample]
  gr <- gr[which(gr$score > deframe(pooled.noise.thresholds[,sample]))]
  point.data[[sample]] <- gr

  gr <- pooled.DLs[pooled.DLs$sample==sample & pooled.DLs$class=="distal"]
  gr <- gr[which(gr$score > deframe(pooled.noise.thresholds[,sample]))]
  point.data[[paste0(sample," distal")]] <- gr

  gr <- pooled.DLs[pooled.DLs$sample==sample & pooled.DLs$class=="proximal"]
  gr <- gr[which(gr$score > deframe(pooled.noise.thresholds[,sample]))]
  point.data[[paste0(sample," proximal")]] <- gr
}

for (n in names(point.data)) {
  point.data[[n]] <- sort(point.data[[n]])
  seqlevels(point.data[[n]],pruning.mode="coarse") <- seqlevels(SNP.data)
  point.data[[n]] <- resize(point.data[[n]], width=resize.width, fix="center")
  point.data[[n]] <- reduce(point.data[[n]],min.gapwidth=0)
}

point.data.assay <- names(point.data)
for (n in pooled.focus.samples) {
  idx <- grep(n,point.data.assay)
  point.data.assay[idx] <- gsub(n,pooled.assay.names[n],point.data.assay[idx])
}

point.data.loc <- rep("genome",length(point.data.assay))
point.data.loc[grep("distal",point.data.assay)] <- "distal"
point.data.loc[grep("proximal",point.data.assay)] <- "proximal"
point.data.loc[which(point.data.assay == "FANTOM5 enhancers")] <- "distal"
point.data.loc[which(point.data.assay == "ENCODE cCRE dELS")] <- "distal"
point.data.loc[c(which(point.data.assay == "ENCODE cCRE PLS"),which(point.data.assay == "ENCODE cCRE pELS"))] <- "proximal"

point.data.assay <- gsub(" distal", "", gsub(" proximal", "", gsub(" PLS", "", gsub(" dELS","",point.data.assay))))
point.data.assay <- gsub(" distal", "", gsub(" proximal", "", point.data.assay))

names(point.data.assay) <- names(point.data.loc) <- names(point.data)

## CRISPR data
CRISPR.pos.data <- readRDS(CRISPR.pos.file)
CRISPR.neg.data <- readRDS(CRISPR.neg.file)

CRISPR.n <- length(CRISPR.pos.data)

```
Calculate eQTL enrichment and recall

```{r}

## Point estimates data

point.eQTL.df <- do.call("rbind", lapply(names(point.data), function(n) {
  fg.olap <- findOverlaps(eQTL.data, point.data[[n]], minoverlap=1)
  bg.olap <- findOverlaps(SNP.data, point.data[[n]], minoverlap=1)
  fg.count <- length(unique(queryHits(fg.olap)))
  bg.count <- length(unique(queryHits(bg.olap)))
  data.frame(enrichment=(fg.count/length(eQTL.data)) / (bg.count/length(SNP.data)),
             recall=fg.count/length(eQTL.data),
             fg.count=fg.count,
             bg.count=bg.count,
             sample=n,
             assay=point.data.assay[n],
             loc=point.data.loc[n])
}))

point.eQTL.df

replicate.eQTL.enrichment.recall.data <- do.call("rbind", lapply(focus.samples, function(sample) {
  
  gr <- DLs[DLs$sample==sample]
  
  scores <- sort(unique(gr$score))
  scores <- scores[seq(1,length(scores),length.out=min(100,length(scores)))]
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
  
  gr.fg.olap <- findOverlaps(eQTL.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(SNP.data, gr, minoverlap=1)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(enrichment=(fg.count/length(eQTL.data))/(bg.count/length(SNP.data)),
               recall=fg.count/length(eQTL.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=sample,
               assay=assay.names[sample])
  }))
}))

pooled.eQTL.enrichment.recall.data <- do.call("rbind", lapply(pooled.focus.samples, function(sample) {
  
  gr <- pooled.DLs[pooled.DLs$sample==sample]
  
  scores <- sort(unique(gr$score))
  scores <- scores[seq(1,length(scores),length.out=min(100,length(scores)))]
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]

  gr.fg.olap <- findOverlaps(eQTL.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(SNP.data, gr, minoverlap=1)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(enrichment=(fg.count/length(eQTL.data))/(bg.count/length(SNP.data)),
               recall=fg.count/length(eQTL.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=sample,
               assay=pooled.assay.names[sample])
  }))
}))

preds.eQTL.enrichment.recall.data <- do.call("rbind", lapply(names(preds.genome.files), function(n) {
  
  gr <- preds[[n]]
  
  scores <- seq(0,1,by=0.01)
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
  
  gr.fg.olap <- findOverlaps(eQTL.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(SNP.data, gr, minoverlap=1)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(enrichment=(fg.count/length(eQTL.data))/(bg.count/length(SNP.data)),
               recall=fg.count/length(eQTL.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=n,
               assay=as.character(preds.genome.names[n]))
  }))
}))

pooled.preds.eQTL.enrichment.recall.data <- do.call("rbind", lapply(names(pooled.preds.genome.files), function(n) {
  
  gr <- pooled.preds[[n]]
  
  scores <- seq(0,1,by=0.01)
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
  
  gr.fg.olap <- findOverlaps(eQTL.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(SNP.data, gr, minoverlap=1)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(enrichment=(fg.count/length(eQTL.data))/(bg.count/length(SNP.data)),
               recall=fg.count/length(eQTL.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=n,
               assay=as.character(pooled.preds.genome.names[n]))
  }))
}))

```


Calculate GWAS enrichment and recall

```{r}

point.GWAS.df <- do.call("rbind", lapply(names(point.data), function(n) {
  fg.olap <- findOverlaps(GWAS.data, point.data[[n]], minoverlap=1)
  bg.olap <- findOverlaps(SNP.data, point.data[[n]], minoverlap=1)
  fg.count <- length(unique(queryHits(fg.olap)))
  bg.count <- length(unique(queryHits(bg.olap)))
  data.frame(enrichment=(fg.count/length(GWAS.data)) / (bg.count/length(SNP.data)),
             recall=fg.count/length(GWAS.data),
             fg.count=fg.count,
             bg.count=bg.count,
             sample=n,
             assay=point.data.assay[n],
             loc=point.data.loc[n])

}))

point.GWAS.df

replicate.GWAS.enrichment.recall.data <- do.call("rbind", lapply(focus.samples, function(sample) {
  
  gr <- DLs[DLs$sample==sample]
  
  scores <- sort(unique(gr$score))
  scores <- scores[seq(1,length(scores),length.out=min(100,length(scores)))]
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
  
  gr.fg.olap <- findOverlaps(GWAS.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(SNP.data, gr, minoverlap=1)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(enrichment=(fg.count/length(GWAS.data))/(bg.count/length(SNP.data)),
               recall=fg.count/length(GWAS.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=sample,
               assay=assay.names[sample])
  }))
}))

pooled.GWAS.enrichment.recall.data <- do.call("rbind", lapply(pooled.focus.samples, function(sample) {
  
  gr <- pooled.DLs[pooled.DLs$sample==sample]
  
  scores <- sort(unique(gr$score))
  scores <- scores[seq(1,length(scores),length.out=min(100,length(scores)))]
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
  
  gr.fg.olap <- findOverlaps(GWAS.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(SNP.data, gr, minoverlap=1)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(enrichment=(fg.count/length(GWAS.data))/(bg.count/length(SNP.data)),
               recall=fg.count/length(GWAS.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=sample,
               assay=pooled.assay.names[sample])
  }))
}))

preds.GWAS.enrichment.recall.data <- do.call("rbind", lapply(names(preds.genome.files), function(n) {
  
  gr <- preds[[n]]
  
  scores <- seq(0,1,by=0.01)
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
  
  gr.fg.olap <- findOverlaps(GWAS.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(SNP.data, gr, minoverlap=1)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(enrichment=(fg.count/length(GWAS.data))/(bg.count/length(SNP.data)),
               recall=fg.count/length(GWAS.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=n,
               assay=as.character(preds.genome.names[n]))
  }))
}))

pooled.preds.GWAS.enrichment.recall.data <- do.call("rbind", lapply(names(pooled.preds.genome.files), function(n) {
  
  gr <- pooled.preds[[n]]
  
  scores <- seq(0,1,by=0.01)
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
  
  gr.fg.olap <- findOverlaps(GWAS.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(SNP.data, gr, minoverlap=1)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(enrichment=(fg.count/length(GWAS.data))/(bg.count/length(SNP.data)),
               recall=fg.count/length(GWAS.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=n,
               assay=as.character(pooled.preds.genome.names[n]))
  }))
}))


```

Calculate CRISPR precision and recall

```{r}

point.CRISPR.df <- do.call("rbind", lapply(names(point.data), function(n) {
  fg.olap <- findOverlaps(CRISPR.pos.data, point.data[[n]], minoverlap=1)
  bg.olap <- findOverlaps(CRISPR.neg.data, point.data[[n]], minoverlap=1)
  #fg.olap <- findOverlaps(CRISPR.pos.data, point.data[[n]], maxgap=1000-resize.width/2)
  #bg.olap <- findOverlaps(CRISPR.neg.data, point.data[[n]], maxgap=1000-resize.width/2)

  fg.count <- length(unique(queryHits(fg.olap)))
  bg.count <- length(unique(queryHits(bg.olap)))
  data.frame(precision=fg.count/(fg.count+bg.count),
             recall=fg.count/length(CRISPR.pos.data),
             fg.count=fg.count,
             bg.count=bg.count,
             sample=n,
             assay=point.data.assay[n],
             loc=point.data.loc[n])
}))

point.CRISPR.df

replicate.CRISPR.precision.recall.data <- do.call("rbind", lapply(focus.samples, function(sample) {
  
  gr <- DLs[DLs$sample==sample]
  
  scores <- sort(unique(gr$score))
  scores <- scores[seq(1,length(scores),length.out=min(100,length(scores)))]
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
  
  gr.fg.olap <- findOverlaps(CRISPR.pos.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(CRISPR.neg.data, gr, minoverlap=1)
  #gr.fg.olap <- findOverlaps(CRISPR.pos.data, gr, maxgap=1000-resize.width/2)
  #gr.bg.olap <- findOverlaps(CRISPR.neg.data, gr, maxgap=1000-resize.width/2)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(precision=fg.count/(fg.count+bg.count),
               recall=fg.count/length(CRISPR.pos.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=sample,
               assay=assay.names[sample])
  }))
}))

pooled.CRISPR.precision.recall.data <- do.call("rbind", lapply(pooled.focus.samples, function(sample) {
  
  gr <- pooled.DLs[pooled.DLs$sample==sample]
  
  scores <- sort(unique(gr$score))
  scores <- scores[seq(1,length(scores),length.out=min(100,length(scores)))]
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
  
  gr.fg.olap <- findOverlaps(CRISPR.pos.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(CRISPR.neg.data, gr, minoverlap=1)
  #gr.fg.olap <- findOverlaps(CRISPR.pos.data, gr, maxgap=1000-resize.width/2)
  #gr.bg.olap <- findOverlaps(CRISPR.neg.data, gr, maxgap=1000-resize.width/2)
  
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(precision=fg.count/(fg.count+bg.count),
               recall=fg.count/length(CRISPR.pos.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=sample,
               assay=pooled.assay.names[sample])
  }))
}))

preds.CRISPR.precision.recall.data <- do.call("rbind", lapply(names(preds.genome.files), function(n) {
  
  gr <- preds[[n]]
  
  scores <- seq(0,1,by=0.01)
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
 
  gr.fg.olap <- findOverlaps(CRISPR.pos.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(CRISPR.neg.data, gr, minoverlap=1)
  #gr.fg.olap <- findOverlaps(CRISPR.pos.data, gr, maxgap=1000-resize.width/2)
  #gr.bg.olap <- findOverlaps(CRISPR.neg.data, gr, maxgap=1000-resize.width/2)
 
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(precision=fg.count/(fg.count+bg.count),
               recall=fg.count/length(CRISPR.pos.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=n,
               assay=as.character(preds.genome.names[n]))
  }))
}))

pooled.preds.CRISPR.precision.recall.data <- do.call("rbind", lapply(names(pooled.preds.genome.files), function(n) {
  
  gr <- pooled.preds[[n]]
  
  scores <- seq(0,1,by=0.01)
  cnt <- sapply(scores, function(sco) sum(gr$score>=sco))
  scores <- scores[cnt>=10]
 
  gr.fg.olap <- findOverlaps(CRISPR.pos.data, gr, minoverlap=1)
  gr.bg.olap <- findOverlaps(CRISPR.neg.data, gr, minoverlap=1)
  #gr.fg.olap <- findOverlaps(CRISPR.pos.data, gr, maxgap=1000-resize.width/2)
  #gr.bg.olap <- findOverlaps(CRISPR.neg.data, gr, maxgap=1000-resize.width/2)
 
  do.call("rbind", lapply(scores, function(sco) {
    
    selection <- which(gr$score>=sco)
    fg.count <- length(unique(queryHits(gr.fg.olap)[which(subjectHits(gr.fg.olap) %in% selection)]))
    bg.count <- length(unique(queryHits(gr.bg.olap)[which(subjectHits(gr.bg.olap) %in% selection)]))
    
    data.frame(precision=fg.count/(fg.count+bg.count),
               recall=fg.count/length(CRISPR.pos.data),
               fg.count=fg.count,
               bg.count=bg.count,
               score=sco,
               sample=n,
               assay=as.character(pooled.preds.genome.names[n]))
  }))
}))


```
Plot eQTL results

```{r}

max.enr <- min(c(max(c(replicate.eQTL.enrichment.recall.data$enrichment,
                       preds.eQTL.enrichment.recall.data$enrichment, point.eQTL.df$enrichment),na.rm=TRUE),90))
min.enr <- min(c(replicate.eQTL.enrichment.recall.data$enrichment,
                 preds.eQTL.enrichment.recall.data$enrichment,point.eQTL.df$enrichment),na.rm=TRUE)

ggplot(replicate.eQTL.enrichment.recall.data, aes(recall, enrichment, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) + xlab(paste0("recall (n=",eQTL.n,")"))
ggsave(paste0("plots/K562_DLs_replicate_eQTL_enrichment_vs_recall_PIP_",eQTL.pip.thres,".pdf"),width=7,height=5)

ggplot(preds.eQTL.enrichment.recall.data, aes(recall, enrichment, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) + xlab(paste0("recall (n=",eQTL.n,")"))
ggsave(paste0("plots/K562_preds_replicate_eQTL_enrichment_vs_recall_PIP_",eQTL.pip.thres,".pdf"),width=7,height=5)

eQTL.r <- sapply(focus.samples, function(n) max(subset(replicate.eQTL.enrichment.recall.data,sample==n)$recall,na.rm=TRUE))
eQTL.mean.enrichment <- sapply(focus.samples, function(n) mean(subset(replicate.eQTL.enrichment.recall.data,sample==n & recall<=min(eQTL.r))$enrichment, na.rm=TRUE))
replicate.eQTL.df <- data.frame(mean_enrichment=eQTL.mean.enrichment,
                                max_recall=eQTL.r,
                                sample=focus.samples,
                                assay=assay.names)

replicate.eQTL.df

eQTL.r <- sapply(focus.samples, function(n) max(subset(preds.eQTL.enrichment.recall.data,sample==n)$recall,na.rm=TRUE))
eQTL.mean.enrichment <- sapply(focus.samples, function(n) mean(subset(preds.eQTL.enrichment.recall.data,sample==n & recall<=min(eQTL.r))$enrichment, na.rm=TRUE))
preds.eQTL.df <- data.frame(mean_enrichment=eQTL.mean.enrichment,
                                max_recall=eQTL.r,
                                sample=focus.samples,
                                assay=preds.genome.names[focus.samples])

preds.eQTL.df

point.eQTL.pooled.df <- subset(point.eQTL.df, !sample %in% as.character(sapply(focus.samples,paste0,c(""," proximal"," distal"))))
point.eQTL.pooled.genome.df <- subset(point.eQTL.pooled.df, loc=="genome")
point.eQTL.pooled.non.genome.df <- subset(point.eQTL.pooled.df, loc!="genome")

max.enr <- min(c(max(c(pooled.eQTL.enrichment.recall.data$enrichment,
                       pooled.preds.eQTL.enrichment.recall.data$enrichment,point.eQTL.df$enrichment),na.rm=TRUE),90))
min.enr <- min(c(pooled.eQTL.enrichment.recall.data$enrichment,
                 pooled.preds.eQTL.enrichment.recall.data$enrichment,point.eQTL.df$enrichment),na.rm=TRUE)

ggplot(pooled.preds.eQTL.enrichment.recall.data, aes(recall, enrichment, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) +
  geom_point(data=point.eQTL.pooled.genome.df) + xlab(paste0("recall (n=",eQTL.n,")"))
ggsave(paste0("plots/K562_pooled_preds_eQTL_enrichment_vs_recall_PIP_",eQTL.pip.thres,"_and_point_estimates_genome.pdf"),width=7,height=5)

ggplot(pooled.eQTL.enrichment.recall.data, aes(recall, enrichment, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) +
  geom_point(data=point.eQTL.pooled.genome.df) + xlab(paste0("recall (n=",eQTL.n,")"))
ggsave(paste0("plots/K562_DLs_pooled_eQTL_enrichment_vs_recall_PIP_",eQTL.pip.thres,"_and_point_estimates_genome.pdf"),width=7,height=5)

ggplot(rbind(pooled.preds.eQTL.enrichment.recall.data, pooled.eQTL.enrichment.recall.data), aes(recall, enrichment, color=assay)) +
  geom_line() + coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) +
  xlab(paste0("recall (n=",eQTL.n,")"))
ggsave(paste0("plots/K562_pooled_preds_vs_DLs_eQTL_enrichment_vs_recall_PIP_",eQTL.pip.thres,".pdf"),width=7,height=5)

eQTL.r <- sapply(pooled.focus.samples, function(n) max(subset(pooled.eQTL.enrichment.recall.data,sample==n)$recall,na.rm=TRUE))
eQTL.mean.enrichment <- sapply(pooled.focus.samples, function(n) mean(subset(pooled.eQTL.enrichment.recall.data,sample==n & recall<=min(eQTL.r))$enrichment, na.rm=TRUE))
pooled.eQTL.df <- data.frame(mean_enrichment=eQTL.mean.enrichment,
                                max_recall=eQTL.r,
                                sample=pooled.focus.samples,
                                assay=pooled.assay.names)

pooled.eQTL.df

eQTL.r <- sapply(pooled.focus.samples, function(n) max(subset(pooled.preds.eQTL.enrichment.recall.data,sample==n)$recall,na.rm=TRUE))
eQTL.mean.enrichment <- sapply(pooled.focus.samples, function(n) mean(subset(pooled.preds.eQTL.enrichment.recall.data,sample==n & recall<=min(eQTL.r))$enrichment, na.rm=TRUE))
pooled.preds.eQTL.df <- data.frame(mean_enrichment=eQTL.mean.enrichment,
                                max_recall=eQTL.r,
                                sample=pooled.focus.samples,
                                assay=pooled.preds.genome.names[pooled.focus.samples])

pooled.preds.eQTL.df

ggplot(point.eQTL.pooled.non.genome.df, aes(recall, enrichment, color=assay, label=sample)) + 
  geom_point(aes(shape=loc)) + theme(aspect.ratio=1) + geom_text_repel(size=2,min.segment.length = 0,color="black") + 
  xlab(paste0("recall (n=",GWAS.n,")"))
ggsave(paste0("plots/K562_eQTL_enrichment_vs_recall_PIP_",eQTL.pip.thres,"_point_estimates_proximal_vs_distal.pdf"),width=8,height=7)

ggplot(point.eQTL.pooled.non.genome.df, aes(sample, recall, fill=loc)) + geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1)) + ylab(paste0("recall (n=",eQTL.n,")"))
ggsave(paste0("plots/K562_eQTL_recall_PIP_",eQTL.pip.thres,"_point_estimates_proximal_vs_distal_bar.pdf"),width=4,height=3)

ggplot(point.eQTL.pooled.non.genome.df, aes(sample, enrichment, fill=loc)) + geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))
ggsave(paste0("plots/K562_eQTL_enrichment_PIP_",eQTL.pip.thres,"_point_estimates_proximal_vs_distal_bar.pdf"),width=4,height=3)

```

Plot GWAS results

```{r}

max.enr <- min(c(max(c(replicate.GWAS.enrichment.recall.data$enrichment,
                       preds.GWAS.enrichment.recall.data$enrichment, point.GWAS.df$enrichment),na.rm=TRUE),25))
min.enr <- min(c(replicate.GWAS.enrichment.recall.data$enrichment,
                 preds.GWAS.enrichment.recall.data$enrichment,point.GWAS.df$enrichment),na.rm=TRUE)

ggplot(replicate.GWAS.enrichment.recall.data, aes(recall, enrichment, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) + xlab(paste0("recall (n=",GWAS.n,")"))
ggsave(paste0("plots/K562_DLs_replicate_GWAS_enrichment_vs_recall_PIP_",GWAS.pip.thres,".pdf"),width=7,height=5)

ggplot(preds.GWAS.enrichment.recall.data, aes(recall, enrichment, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) + xlab(paste0("recall (n=",GWAS.n,")"))
ggsave(paste0("plots/K562_preds_replicate_GWAS_enrichment_vs_recall_PIP_",GWAS.pip.thres,".pdf"),width=7,height=5)

GWAS.r <- sapply(focus.samples, function(n) max(subset(replicate.GWAS.enrichment.recall.data,sample==n)$recall,na.rm=TRUE))
GWAS.mean.enrichment <- sapply(focus.samples, function(n) mean(subset(replicate.GWAS.enrichment.recall.data,sample==n & recall<=min(GWAS.r))$enrichment, na.rm=TRUE))
replicate.GWAS.df <- data.frame(mean_enrichment=GWAS.mean.enrichment,
                                max_recall=GWAS.r,
                                sample=focus.samples,
                                assay=assay.names)

replicate.GWAS.df

GWAS.r <- sapply(focus.samples, function(n) max(subset(preds.GWAS.enrichment.recall.data,sample==n)$recall,na.rm=TRUE))
GWAS.mean.enrichment <- sapply(focus.samples, function(n) mean(subset(preds.GWAS.enrichment.recall.data,sample==n & recall<=min(GWAS.r))$enrichment, na.rm=TRUE))
preds.GWAS.df <- data.frame(mean_enrichment=GWAS.mean.enrichment,
                                max_recall=GWAS.r,
                                sample=focus.samples,
                                assay=preds.genome.names[focus.samples])

preds.GWAS.df

point.GWAS.pooled.df <- subset(point.GWAS.df, !sample %in% as.character(sapply(focus.samples,paste0,c(""," proximal"," distal"))))
point.GWAS.pooled.genome.df <- subset(point.GWAS.pooled.df, loc=="genome")
point.GWAS.pooled.non.genome.df <- subset(point.GWAS.pooled.df, loc!="genome")

max.enr <- min(c(max(c(pooled.GWAS.enrichment.recall.data$enrichment,
                       pooled.preds.GWAS.enrichment.recall.data$enrichment,point.GWAS.df$enrichment),na.rm=TRUE),25))
min.enr <- min(c(pooled.GWAS.enrichment.recall.data$enrichment,
                 pooled.preds.GWAS.enrichment.recall.data$enrichment,point.GWAS.df$enrichment),na.rm=TRUE)

ggplot(pooled.preds.GWAS.enrichment.recall.data, aes(recall, enrichment, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) +
  geom_point(data=point.GWAS.pooled.genome.df) + xlab(paste0("recall (n=",GWAS.n,")"))
ggsave(paste0("plots/K562_pooled_preds_GWAS_enrichment_vs_recall_PIP_",GWAS.pip.thres,"_and_point_estimates_genome.pdf"),width=7,height=5)

ggplot(pooled.GWAS.enrichment.recall.data, aes(recall, enrichment, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) +
  geom_point(data=point.GWAS.pooled.genome.df) + xlab(paste0("recall (n=",GWAS.n,")"))
ggsave(paste0("plots/K562_DLs_pooled_GWAS_enrichment_vs_recall_PIP_",GWAS.pip.thres,"_and_point_estimates_genome.pdf"),width=7,height=5)

ggplot(rbind(pooled.preds.GWAS.enrichment.recall.data, pooled.GWAS.enrichment.recall.data), aes(recall, enrichment, color=assay)) +
  geom_line() + coord_cartesian(ylim=c(min.enr,max.enr)) + theme(aspect.ratio=1) +
  xlab(paste0("recall (n=",GWAS.n,")"))
ggsave(paste0("plots/K562_pooled_preds_vs_DLs_GWAS_enrichment_vs_recall_PIP_",GWAS.pip.thres,".pdf"),width=7,height=5)

GWAS.r <- sapply(pooled.focus.samples, function(n) max(subset(pooled.GWAS.enrichment.recall.data,sample==n)$recall,na.rm=TRUE))
GWAS.mean.enrichment <- sapply(pooled.focus.samples, function(n) mean(subset(pooled.GWAS.enrichment.recall.data,sample==n & recall<=min(GWAS.r))$enrichment, na.rm=TRUE))
pooled.GWAS.df <- data.frame(mean_enrichment=GWAS.mean.enrichment,
                                max_recall=GWAS.r,
                                sample=pooled.focus.samples,
                                assay=pooled.assay.names)

pooled.GWAS.df

GWAS.r <- sapply(pooled.focus.samples, function(n) max(subset(pooled.preds.GWAS.enrichment.recall.data,sample==n)$recall,na.rm=TRUE))
GWAS.mean.enrichment <- sapply(pooled.focus.samples, function(n) mean(subset(pooled.preds.GWAS.enrichment.recall.data,sample==n & recall<=min(GWAS.r))$enrichment, na.rm=TRUE))
pooled.preds.GWAS.df <- data.frame(mean_enrichment=GWAS.mean.enrichment,
                                max_recall=GWAS.r,
                                sample=pooled.focus.samples,
                                assay=pooled.preds.genome.names[pooled.focus.samples])

pooled.preds.GWAS.df

ggplot(point.GWAS.pooled.non.genome.df, aes(recall, enrichment, color=assay, label=sample)) + 
  geom_point(aes(shape=loc)) + theme(aspect.ratio=1) + geom_text_repel(size=2,min.segment.length = 0,color="black") + 
  xlab(paste0("recall (n=",GWAS.n,")"))
ggsave(paste0("plots/K562_GWAS_enrichment_vs_recall_PIP_",GWAS.pip.thres,"_point_estimates_proximal_vs_distal.pdf"),width=8,height=7)

ggplot(point.GWAS.pooled.non.genome.df, aes(sample, recall, fill=loc)) + geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1)) + ylab(paste0("recall (n=",GWAS.n,")"))
ggsave(paste0("plots/K562_GWAS_recall_PIP_",GWAS.pip.thres,"_point_estimates_proximal_vs_distal_bar.pdf"),width=4,height=3)

ggplot(point.GWAS.pooled.non.genome.df, aes(sample, enrichment, fill=loc)) + geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))
ggsave(paste0("plots/K562_GWAS_enrichment_PIP_",GWAS.pip.thres,"_point_estimates_proximal_vs_distal_bar.pdf"),width=4,height=3)

```

Plot CRISPR results

```{r}

max.prec <- min(c(max(c(replicate.CRISPR.precision.recall.data$precision,
                       preds.CRISPR.precision.recall.data$precision, point.CRISPR.df$precision),na.rm=TRUE),0.5))
min.prec <- min(c(replicate.CRISPR.precision.recall.data$precision,
                 preds.CRISPR.precision.recall.data$precision,point.CRISPR.df$precision),na.rm=TRUE)

ggplot(replicate.CRISPR.precision.recall.data, aes(recall, precision, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.prec,max.prec)) + theme(aspect.ratio=1) + xlab(paste0("recall (n=",CRISPR.n,")"))
ggsave(paste0("plots/K562_DLs_replicate_CRISPR_precision_vs_recall.pdf"),width=7,height=5)

ggplot(preds.CRISPR.precision.recall.data, aes(recall, precision, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.prec,max.prec)) + theme(aspect.ratio=1) + xlab(paste0("recall (n=",CRISPR.n,")"))
ggsave(paste0("plots/K562_preds_replicate_CRISPR_precision_vs_recall.pdf"),width=7,height=5)

ggplot(preds.CRISPR.precision.recall.data, aes(recall, precision, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.prec,max.prec)) + theme(aspect.ratio=1) + xlab(paste0("recall (n=",CRISPR.n,")"))
ggsave(paste0("plots/K562_preds_replicate_CRISPR_precision_vs_recall.pdf"),width=7,height=5)

subset(preds.CRISPR.precision.recall.data, score %in% c(0.1,0.2,0.3,0.4,0.5))

CRISPR.r <- sapply(focus.samples, function(n) max(subset(replicate.CRISPR.precision.recall.data,sample==n)$recall,na.rm=TRUE))
CRISPR.mean.precision <- sapply(focus.samples, function(n) mean(subset(replicate.CRISPR.precision.recall.data,sample==n & recall<=min(CRISPR.r))$precision, na.rm=TRUE))
replicate.CRISPR.df <- data.frame(mean_precision=CRISPR.mean.precision,
                                max_recall=CRISPR.r,
                                sample=focus.samples,
                                assay=assay.names)

replicate.CRISPR.df

CRISPR.r <- sapply(focus.samples, function(n) max(subset(preds.CRISPR.precision.recall.data,sample==n)$recall,na.rm=TRUE))
CRISPR.mean.precision <- sapply(focus.samples, function(n) mean(subset(preds.CRISPR.precision.recall.data,sample==n & recall<=min(CRISPR.r))$precision, na.rm=TRUE))
preds.CRISPR.df <- data.frame(mean_precision=CRISPR.mean.precision,
                                max_recall=CRISPR.r,
                                sample=focus.samples,
                                assay=preds.genome.names[focus.samples])

preds.CRISPR.df

point.CRISPR.pooled.df <- subset(point.CRISPR.df, !sample %in% as.character(sapply(focus.samples,paste0,c(""," proximal"," distal"))))
point.CRISPR.pooled.genome.df <- subset(point.CRISPR.pooled.df, loc=="genome")
point.CRISPR.pooled.non.genome.df <- subset(point.CRISPR.pooled.df, loc!="genome")

max.prec <- min(c(max(c(pooled.CRISPR.precision.recall.data$precision,
                       pooled.preds.CRISPR.precision.recall.data$precision,point.CRISPR.df$precision),na.rm=TRUE),0.5))
min.prec <- min(c(pooled.CRISPR.precision.recall.data$precision,
                 pooled.preds.CRISPR.precision.recall.data$precision,point.CRISPR.df$precision),na.rm=TRUE)

ggplot(pooled.preds.CRISPR.precision.recall.data, aes(recall, precision, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.prec,max.prec)) + theme(aspect.ratio=1) +
  geom_point(data=point.CRISPR.pooled.genome.df) + xlab(paste0("recall (n=",CRISPR.n,")"))
ggsave(paste0("plots/K562_pooled_preds_CRISPR_precision_vs_recall_and_point_estimates_genome.pdf"),width=7,height=5)

ggplot(pooled.CRISPR.precision.recall.data, aes(recall, precision, color=assay)) + geom_line(aes(group=sample)) +
  coord_cartesian(ylim=c(min.prec,max.prec)) + theme(aspect.ratio=1) +
  geom_point(data=point.CRISPR.pooled.genome.df) + xlab(paste0("recall (n=",CRISPR.n,")"))
ggsave(paste0("plots/K562_DLs_pooled_CRISPR_precision_vs_recall_and_point_estimates_genome.pdf"),width=7,height=5)

ggplot(rbind(pooled.preds.CRISPR.precision.recall.data, pooled.CRISPR.precision.recall.data), aes(recall, precision, color=assay)) +
  geom_line() + coord_cartesian(ylim=c(min.prec,max.prec)) + theme(aspect.ratio=1) +
  xlab(paste0("recall (n=",CRISPR.n,")"))
ggsave(paste0("plots/K562_pooled_preds_vs_DLs_CRISPR_precision_vs_recall.pdf"),width=7,height=5)

subset(pooled.preds.CRISPR.precision.recall.data, score %in% c(0.1,0.2,0.3,0.4,0.5))

CRISPR.r <- sapply(pooled.focus.samples, function(n) max(subset(pooled.CRISPR.precision.recall.data,sample==n)$recall,na.rm=TRUE))
CRISPR.mean.precision <- sapply(pooled.focus.samples, function(n) mean(subset(pooled.CRISPR.precision.recall.data,sample==n & recall<=min(CRISPR.r))$precision, na.rm=TRUE))
pooled.CRISPR.df <- data.frame(mean_precision=CRISPR.mean.precision,
                                max_recall=CRISPR.r,
                                sample=pooled.focus.samples,
                                assay=pooled.assay.names)

pooled.CRISPR.df

CRISPR.r <- sapply(pooled.focus.samples, function(n) max(subset(pooled.preds.CRISPR.precision.recall.data,sample==n)$recall,na.rm=TRUE))
CRISPR.mean.precision <- sapply(pooled.focus.samples, function(n) mean(subset(pooled.preds.CRISPR.precision.recall.data,sample==n & recall<=min(CRISPR.r))$precision, na.rm=TRUE))
pooled.preds.CRISPR.df <- data.frame(mean_precision=CRISPR.mean.precision,
                                max_recall=CRISPR.r,
                                sample=pooled.focus.samples,
                                assay=pooled.preds.genome.names[pooled.focus.samples])

pooled.preds.CRISPR.df

ggplot(point.CRISPR.pooled.non.genome.df, aes(recall, precision, color=assay, label=sample)) + 
  geom_point(aes(shape=loc)) + theme(aspect.ratio=1) + geom_text_repel(size=2,min.segment.length = 0,color="black") + 
  xlab(paste0("recall (n=",CRISPR.n,")"))
ggsave(paste0("plots/K562_CRISPR_precision_vs_recall_point_estimates_proximal_vs_distal.pdf"),width=8,height=7)

ggplot(point.CRISPR.pooled.non.genome.df, aes(sample, recall, fill=loc)) + geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1)) + ylab(paste0("recall (n=",CRISPR.n,")"))
ggsave(paste0("plots/K562_CRISPR_recall_point_estimates_proximal_vs_distal_bar.pdf"),width=4,height=3)

ggplot(point.CRISPR.pooled.non.genome.df, aes(sample, precision, fill=loc)) + geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle=45,vjust=1,hjust=1))
ggsave(paste0("plots/K562_CRISPR_precision_point_estimates_proximal_vs_distal_bar.pdf"),width=4,height=3)

```

