---
title: "1.5.TrackPlotting"
output: html_document
date: "2024-02-29"
---


```{r}
library(CAGEfightR)

#CAGEfighR extensions
setwd("/home/mhf817")
sep <- .Platform$file.sep
cfr.extensions.dir <- "/home/mhf817/CAGEfightR_extensions"
source(paste(cfr.extensions.dir, "utils.R", sep = sep))
source(paste(cfr.extensions.dir, "support.R", sep = sep))
source(paste(cfr.extensions.dir, "cumulative.R", sep = sep))
source(paste(cfr.extensions.dir, "decompose.R", sep = sep))
source(paste(cfr.extensions.dir, "enhancers.R", sep = sep))
source(paste(cfr.extensions.dir, "noise.R", sep = sep))
source(paste(cfr.extensions.dir, "coverage.R", sep = sep))
source(paste(cfr.extensions.dir, "complexity.R", sep = sep))
source(paste(cfr.extensions.dir, "subsample.R", sep = sep))
source(paste(cfr.extensions.dir, "dispersion.R", sep = sep))


#Annotations
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

#Packages for plotting
library(CAGEfightR)
library(epistack)
library(BiocParallel)
library(dplyr)
library(reshape2)
library(limma)
library(ggplot2)
library(Matrix)
library(corrplot)
library(stringr)
library(gridExtra)
library(Gviz)



custom.col <- c("#FFDB6D", "#C4961A", "#F4EDCA", 
                "#D16103", "#C3D7A4", "#52854C", "#4E84C4", "#293352","grey")


gm.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#DF613F","#DF5643","#DD4425","#92B9C9","#76A5B6","#004352","#29A957","#008E37","#007A30","#4F5D5C","#444E4C","#3D4138",
                     "#AC97C2","#977FB4","#7D62A3")
                     
gm.pooled.pal <- c("#FF8D00","#FF4425","#00439B","#009072","#878784","#7D62D0")

gm.full.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#FF8D00","#DF613F","#DF5643","#DD4425","#FF4425","#92B9C9","#76A5B6","#004352","#00439B","#29A957","#008E37","#007A30","#009072","#4F5D5C","#444E4C","#3D4138","#878784","#AC97C2","#977FB4","#7D62A3","#7D62D0")



k.full.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#FF8D00","#DF613F","#DF5643","#DD4425","#FF4425","#92B9C9","#76A5B6","#004352","#00439B","#29A957","#008E37","#007A30","#4F5D5C")

#Set working directory
setwd("/maps/projects/ralab/data/projects/nucleiCAGEproject/1.CTSSs/")
```


#Start simple with k562 pooled tracks
```{r}
k562.p.CTSSs <- readRDS("poolSub.combined.k562.CTSSs.rds")

k562.TCs <- readRDS("../3.DivergentLoci/repSub.k562.DLs.TCs.rds")
```


```{r}
#Create the stable treacks 
axis_track <- GenomeAxisTrack()     

tx_track <- GeneRegionTrack(txdb,                
                            name = "Gene Models",
                            col = NA,       
                            stacking="dense",
                            fill = "bisque4",    
                            shape = "arrow",     
                            showId = TRUE)  
```

```{r}
#Select plot region
plot_region <- k562.TCs %>% subset(txType=="intron" & dhs.olap>0 & score>10 & abs(directionality)<=0.1 & divergent==TRUE & sample=="K562_N") %>%      
    .[2] %>%                                  
    resize(width=20500,fix="center") 


c_1M_ctss <- k562.p.CTSSs[,k562.p.CTSSs$pooled=="yes" & k562.p.CTSSs$Type=="C,C,C"]  %>% calcPooled() %>%       
    rowRanges %>%                             
    subsetByOverlaps(plot_region) %>%         
    trackCTSS(name = "C_1M")       

n_1M_ctss <- k562.p.CTSSs[,k562.p.CTSSs$pooled=="yes" & k562.p.CTSSs$Type=="N,N,N"]  %>% calcPooled() %>%       
    rowRanges %>%                             
    subsetByOverlaps(plot_region) %>%         
    trackCTSS(name = "N_1M")       


c_1M_ctss_enhancer <- k562.p.CTSSs[,k562.p.CTSSs$pooled=="yes" & k562.p.CTSSs$Type=="C,C,C"]  %>% calcPooled() %>%       
    rowRanges %>%                             
    subsetByOverlaps(resize(plot_region, width=400, fix="center")) %>%         
    trackCTSS(name = "C_1M", ylim=c(-0.06,0.06))       

n_1M_ctss_enhancer <- k562.p.CTSSs[,k562.p.CTSSs$pooled=="yes" & k562.p.CTSSs$Type=="N,N,N"]  %>% calcPooled() %>%       
    rowRanges %>%                             
    subsetByOverlaps(resize(plot_region, width=400, fix="center")) %>%         
    trackCTSS(name = "N_1M", ylim=c(-0.06,0.06))       




cluster_track <- k562.TCs %>% swapRanges()    %>%      
    subsetByOverlaps(swapRanges(plot_region)) %>%
  .[1] %>% resize(width=400, fix="center") %>%
    trackClusters(name = "Clusters",          
                  col = NA,                   
                  showId=TRUE)  

plotTracks(list(axis_track,                   
                c_1M_ctss,
                n_1M_ctss,
                c_1M_ctss_enhancer,
                n_1M_ctss_enhancer,
                cluster_track,                
                tx_track),                    
           from = start(plot_region),         
           to=end(plot_region),               
           chromosome = seqnames(plot_region))

```





```{r}
#Select plot region
plot_region <- k562.TCs %>% subset(txType=="intergenic" & dhs.olap>0 & score>10 & abs(directionality)<=0.1 & divergent==TRUE & sample=="K562_N") %>%      
    .[2] %>%                                  
    promoters(upstream=100000, downstream=1000) 


c_1M_ctss <- k562.p.CTSSs[,k562.p.CTSSs$pooled=="yes" & k562.p.CTSSs$Type=="C,C,C"]  %>% calcPooled() %>%       
    rowRanges %>%                             
    subsetByOverlaps(plot_region) %>%         
    trackCTSS(name = "C_1M")       

n_1M_ctss <- k562.p.CTSSs[,k562.p.CTSSs$pooled=="yes" & k562.p.CTSSs$Type=="N,N,N"]  %>% calcPooled() %>%       
    rowRanges %>%                             
    subsetByOverlaps(plot_region) %>%         
    trackCTSS(name = "N_1M")       


c_1M_ctss_enhancer <- k562.p.CTSSs[,k562.p.CTSSs$pooled=="yes" & k562.p.CTSSs$Type=="C,C,C"]  %>% calcPooled() %>%       
    rowRanges %>%                             
    subsetByOverlaps(resize(swapRanges(plot_region), width=400, fix="center")) %>%         
    trackCTSS(name = "C_1M",plusColor = "#FF8D00", minusColor="#FF8D00")       

n_1M_ctss_enhancer <- k562.p.CTSSs[,k562.p.CTSSs$pooled=="yes" & k562.p.CTSSs$Type=="N,N,N"]  %>% calcPooled() %>%       
    rowRanges %>%                             
    subsetByOverlaps(resize(swapRanges(plot_region), width=400, fix="center")) %>%        
    trackCTSS(name = "N_1M",plusColor = "#FF4425", minusColor="#FF4425")       




cluster_track <- k562.TCs  %>%      
    subsetByOverlaps(plot_region) %>%
  subset(score>10& sample=="K562_N") %>%
    trackClusters(name = "Clusters",          
                  col = NA,                   
                  showId=TRUE)  

plotTracks(list(axis_track,                   
                c_1M_ctss,
                n_1M_ctss,
                cluster_track,                
                tx_track),                    
           from = start(plot_region),         
           to=end(plot_region),               
           chromosome = seqnames(plot_region), background.title = "transparent", fontcolor="black", col.title="black", col.axis="black",legend=FALSE)

```