---
title: "Remove singletons from CTSS objects"
output: html_document
date: "2024-04-24"
---


```{r}
library(CAGEfightR)

#CAGEfighR extensions
setwd("/home/mhf817")
sep <- .Platform$file.sep
cfr.extensions.dir <- "/home/mhf817/CAGEfightR_extensions"
source(paste(cfr.extensions.dir, "utils.R", sep = sep))
source(paste(cfr.extensions.dir, "support.R", sep = sep))
source(paste(cfr.extensions.dir, "cumulative.R", sep = sep))
source(paste(cfr.extensions.dir, "decompose.R", sep = sep))
source(paste(cfr.extensions.dir, "enhancers.R", sep = sep))
source(paste(cfr.extensions.dir, "noise.R", sep = sep))
source(paste(cfr.extensions.dir, "coverage.R", sep = sep))
source(paste(cfr.extensions.dir, "complexity.R", sep = sep))
source(paste(cfr.extensions.dir, "subsample.R", sep = sep))
source(paste(cfr.extensions.dir, "dispersion.R", sep = sep))


#Annotations
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

#Packages for plotting
library(CAGEfightR)
library(epistack)
library(BiocParallel)
library(dplyr)
library(reshape2)
library(limma)
library(ggplot2)
library(Matrix)
library(corrplot)


custom.col <- c("#FFDB6D", "#C4961A", "#F4EDCA", 
                "#D16103", "#C3D7A4", "#52854C", "#4E84C4", "#293352","grey")


#Function for pooling replicates
poolReplicates <- function(object, replicates, inputAssay="counts") {
    
    ## dimensions
    assert_that(ncol(object)==length(replicates),
                length(unique(replicates))>1)


    message("Calculating pooled counts...")
    a <- do.call("cbind", lapply(unique(replicates), function(b) 
      Matrix::rowSums(assay(object,inputAssay)[,replicates==b,drop=FALSE])))
    a <- as(a, "sparseMatrix")
    colnames(a) <- unique(replicates)

    message("Create a pasted design matrix...")
    c <- do.call("rbind", lapply(unique(replicates), function(b) 
      apply(colData(object)[replicates==b,], 2 , paste , collapse = "," )))

    rse <- SummarizedExperiment(assays=SimpleList(counts=a),
                            rowRanges=rowRanges(object), colData=as.data.frame(c))
    
    rse <- calcTotalTags(rse)
    
    rse
}

#Alternative subsampling to deal with dropped rows
subsampleTarget <- function(object, inputAssay = "counts", target) {

    assert_that(methods::is(object, "SummarizedExperiment"),
                inputAssay %in% assayNames(object),
                is.numeric(target), target > 0)
    
    a <- assay(object,inputAssay)
    n <- ncol(a)
    nz <- lapply(1:n, function(i) nonzero(a[,i,drop=FALSE])[,1])
    s <- Matrix::colSums(a)
    d <- unlist(lapply(1:n, function(i) {
        if (s[i]<=target)
            a[nz[[i]],i]
        else
            rbinom(length(nz[[i]]),a[nz[[i]],i], target/s[i])
    }))
    keep <- which(sapply(nz,length)>0)
    
    # Create a matrix to store the subsampled counts, ensuring all rows are retained
    new_matrix <- Matrix::sparseMatrix(
        i = unlist(nz),
        j = unlist(lapply(keep, function(i) rep(i, length(nz[[i]])))),
        x = d, 
        dims = dim(a),  # Preserve the original dimensions
        dimnames = list(rownames(a), colnames(a)[keep])
    )
    
    # Replace the original assay with the new matrix
    assay(object, inputAssay) <- new_matrix
    
    # Recalculate the total count of reads for each sample
    object <- calcTotalTags(object)
    
    object
}

#Set working directory
setwd("/maps/projects/ralab/data/projects/nucleiCAGEproject/1.CTSSs/")
```







#K562
```{r}
#Read in design for k562
design <- read.table("K562.design.txt",sep="\t",header=T)

#Filter and format for use
design <- design[design$use=="yes",]
row.names(design) <- design$ID

#Format bw_files
plus_files <- design$bw_plus
minus_files <- design$bw_minus
names(plus_files) <- names(minus_files) <- row.names(design)

bw_plus <- BigWigFileList(plus_files)
bw_minus <- BigWigFileList(minus_files)

```


```{r}
#Quantify CTSSs with no reference genome set
register(MulticoreParam(workers=10))

k562.CTSSs <- quantifyCTSSs(plusStrand = bw_plus,
                       minusStrand = bw_minus,
                       design = design)


k562.CTSSs <- k562.CTSSs %>% calcTPM() %>% calcPooled()

```



```{r}
#Remove non standard chromosomes 
keep <- seqlevels(k562.CTSSs)[1:23]

k562.CTSSs <- keepSeqlevels(k562.CTSSs, keep, pruning.mode = "coarse")
```



```{r}
#Pool replicates
k562.p.CTSSs <- poolReplicates(k562.CTSSs,
                               replicates=paste(colData(k562.CTSSs)$Cell.line,colData(k562.CTSSs)$Type, sep="_"))

k562.p.CTSSs <- calcTPM(k562.p.CTSSs)

```





```{r}
#make combined objects
colData(k562.CTSSs)$pooled <- "no"
colData(k562.p.CTSSs)$pooled <- "yes"

k562.combined.CTSSs <- cbind(k562.CTSSs,k562.p.CTSSs)

#Find minimum seq depths
k562.combined.CTSSs <- calcTotalTags(k562.combined.CTSSs)

```


```{r}
#Subsample both original and pooled to minimum common depth
set.seed(1337)

#subsample combined. Three sets, lowest CAGE rep and lowest pooled (excluding proCap and groCap)
rep.min <- min(colData(k562.combined.CTSSs)$totalTags[colData(k562.combined.CTSSs)$pooled=="no"& !colData(k562.combined.CTSSs)$method %in% c("ProCap","GroCap")]) #28619974
pool.min <- min(colData(k562.combined.CTSSs)$totalTags[colData(k562.combined.CTSSs)$pooled=="yes" & !colData(k562.combined.CTSSs)$method %in% c("ProCap,ProCap","GroCap")]) #96351121

k562.combined.repSub.CTSSs<- subsampleTarget(k562.combined.CTSSs, target = rep.min)
k562.combined.poolSub.CTSSs<- subsampleTarget(k562.combined.CTSSs, target = pool.min)


k562.combined.repSub.CTSSs <- calcTPM(k562.combined.repSub.CTSSs)
k562.combined.poolSub.CTSSs <- calcTPM(k562.combined.poolSub.CTSSs)


#Create new assay with counts where 1 counts become 0
rmSingletons <- function(rse, inputAssay = "counts") {
  rmS <- assay(rse, inputAssay)
  # Find the indices where values are equal to 1
  idx <- which(rmS == 1, arr.ind = TRUE)
  # Replace the values at those indices with 0
  rmS[idx] <- 0
  # Assign the modified assay back to the SummarizedExperiment object
  assay(rse, "counts.noSingletons") <- rmS
  rse
}

k562.combined.repSub.CTSSs <- rmSingletons(k562.combined.repSub.CTSSs)
k562.combined.poolSub.CTSSs <- rmSingletons(k562.combined.poolSub.CTSSs)
```






```{r}
#Save as new objects

saveRDS(k562.combined.CTSSs, "all.combined.k562.CTSSs.rds")
saveRDS(k562.combined.repSub.CTSSs, "repSub.combined.k562.CTSSs.rmSingletons.rds")
saveRDS(k562.combined.poolSub.CTSSs, "poolSub.combined.k562.CTSSs.rmSingletons.rds")


```



#########
#GM12878
#########


```{r}
#Read in design for GM12878
design <- read.table("GM12878.design.txt",sep="\t",header=T)

#Filter and format for use
design <- design[design$use=="yes",]
row.names(design) <- paste(design$ID,design$Seq_run,sep="_")

#Format bw_files
plus_files <- design$bw_plus
minus_files <- design$bw_minus
names(plus_files) <- names(minus_files) <- row.names(design)

bw_plus <- BigWigFileList(plus_files)
bw_minus <- BigWigFileList(minus_files)

```




```{r}
#Quantify CTSSs with no reference genome set
register(MulticoreParam(workers=20))

GM12878.CTSSs <- quantifyCTSSs(plusStrand = bw_plus,
                       minusStrand = bw_minus,
                       design = design)


GM12878.CTSSs <- GM12878.CTSSs %>% calcTPM() %>% calcPooled()

GM12878.CTSSs <- keepSeqlevels(GM12878.CTSSs, keep, pruning.mode = "coarse")


```





```{r}
#Pool only based on reqsequencing
GM12878.pID.CTSSs <- poolReplicates(GM12878.CTSSs,colData(GM12878.CTSSs)$ID)

GM12878.pID.CTSSs <- calcTPM(GM12878.pID.CTSSs)
#Pool replicates
GM12878.p.CTSSs <- poolReplicates(GM12878.CTSSs,
                               replicates=paste(colData(GM12878.CTSSs)$Cell.line,colData(GM12878.CTSSs)$cell_count,colData(GM12878.CTSSs)$Type, sep="_"))

GM12878.p.CTSSs <- calcTPM(GM12878.p.CTSSs)


```



```{r}
#Main indicates if part of main analysis. Removing Triptolide and low input
colData(GM12878.pID.CTSSs)$main <- "yes"
colData(GM12878.pID.CTSSs)$main[colData(GM12878.pID.CTSSs)$Type %in% c("Cap_align","ctrl","trip")| colData(GM12878.pID.CTSSs)$cell_count %in% c("50K","250K,250K")] <- "no"
colData(GM12878.pID.CTSSs)$pooled <- "no"
#Subsample
colData(GM12878.p.CTSSs)$main <- "yes"
colData(GM12878.p.CTSSs)$main[colData(GM12878.p.CTSSs)$Type %in% c("Cap_align","ctrl,ctrl,ctrl","trip,trip,trip,trip")| colData(GM12878.p.CTSSs)$cell_count %in% c("50K,50K,50K","250K,250K,250K,250K,250K,250K")] <- "no"
colData(GM12878.p.CTSSs)$pooled <- "yes"


GM12878.combined.CTSSs <- cbind(GM12878.p.CTSSs,GM12878.pID.CTSSs)
GM12878.combined.CTSSs <- calcTotalTags(GM12878.combined.CTSSs)

rep.min <- min(colData(GM12878.combined.CTSSs)$totalTags[colData(GM12878.combined.CTSSs)$main=="yes" & colData(GM12878.combined.CTSSs)$pooled=="no"]) #28453942
pool.min <- min(colData(GM12878.combined.CTSSs)$totalTags[colData(GM12878.combined.CTSSs)$main=="yes" & colData(GM12878.combined.CTSSs)$pooled=="yes"]) #104774632

GM12878.combined.repSub.CTSSs<- subsampleTarget(GM12878.combined.CTSSs, target = rep.min)
GM12878.combined.poolSub.CTSSs<- subsampleTarget(GM12878.combined.CTSSs, target = pool.min)

GM12878.combined.repSub.CTSSs <- calcTPM(GM12878.combined.repSub.CTSSs)
GM12878.combined.poolSub.CTSSs <- calcTPM(GM12878.combined.poolSub.CTSSs)
```



```{r}
#remove singletons

GM12878.combined.repSub.CTSSs <- rmSingletons(GM12878.combined.repSub.CTSSs)
GM12878.combined.poolSub.CTSSs <- rmSingletons(GM12878.combined.poolSub.CTSSs)
```

```{r}
#Save as new objects
saveRDS(GM12878.combined.CTSSs, "all.combined.GM12878.CTSSs.rds")
saveRDS(GM12878.combined.repSub.CTSSs, "repSub.combined.GM12878.CTSSs.rmSingletons.rds")
saveRDS(GM12878.combined.poolSub.CTSSs, "poolSub.combined.GM12878.CTSSs.rmSingletons.rds")


```


