---
title: "1.3.2.Noise"
output: html_document
date: "2024-01-31"
---

```{r}
library(CAGEfightR)

#CAGEfighR extensions
setwd("/home/mhf817")
sep <- .Platform$file.sep
cfr.extensions.dir <- "/home/mhf817/CAGEfightR_extensions"
source(paste(cfr.extensions.dir, "utils.R", sep = sep))
source(paste(cfr.extensions.dir, "support.R", sep = sep))
source(paste(cfr.extensions.dir, "cumulative.R", sep = sep))
source(paste(cfr.extensions.dir, "decompose.R", sep = sep))
source(paste(cfr.extensions.dir, "enhancers.R", sep = sep))
source(paste(cfr.extensions.dir, "noise.R", sep = sep))
source(paste(cfr.extensions.dir, "coverage.R", sep = sep))
source(paste(cfr.extensions.dir, "complexity.R", sep = sep))
source(paste(cfr.extensions.dir, "subsample.R", sep = sep))
source(paste(cfr.extensions.dir, "dispersion.R", sep = sep))


#Annotations
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

#Packages for plotting
library(CAGEfightR)
library(epistack)
library(BiocParallel)
library(dplyr)
library(reshape2)
library(limma)
library(ggplot2)
library(Matrix)
library(corrplot)
library(stringr)
library(gridExtra)



custom.col <- c("#FFDB6D", "#C4961A", "#F4EDCA", 
                "#D16103", "#C3D7A4", "#52854C", "#4E84C4", "#293352","grey")


gm.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#DF613F","#DF5643","#DD4425","#92B9C9","#76A5B6","#004352","#29A957","#008E37","#007A30","#4F5D5C","#444E4C","#3D4138",
                     "#AC97C2","#977FB4","#7D62A3")
                     
gm.pooled.pal <- c("#FF8D00","#FF4425","#00439B","#009072","#878784","#7D62D0")

gm.full.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#FF8D00","#DF613F","#DF5643","#DD4425","#FF4425","#92B9C9","#76A5B6","#004352","#00439B","#29A957","#008E37","#007A30","#009072","#4F5D5C","#444E4C","#3D4138","#878784","#AC97C2","#977FB4","#7D62A3","#7D62D0")



k.full.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#FF8D00","#DF613F","#DF5643","#DD4425","#FF4425","#92B9C9","#76A5B6","#004352","#00439B","#29A957","#008E37","#007A30","#4F5D5C")

#Set working directory
setwd("/maps/projects/ralab/data/projects/nucleiCAGEproject/1.CTSSs/")
```


#K562
```{r}
#Read in pre made CTSS objects
k562.CTSSs <- readRDS("all.combined.k562.CTSSs.rds")
k562.s.CTSSs <- readRDS("repSub.combined.k562.CTSSs.rds")
k562.p.CTSSs <- readRDS("poolSub.combined.k562.CTSSs.rds")
```



```{r}
#Read in DHS bed file form encode 
k562.dhs <- read.table("../0.External_resources/E123-DNase.macs2.hg38.narrowPeak")
colnames(k562.dhs) <- c("chr","start","end")
k562.dhs <- GRanges(k562.dhs[,1:3])
k562.dhs$thick <- IRanges(start=start(k562.dhs)+((end(k562.dhs)-start(k562.dhs))/2))
```



```{r}
#Remove non standard chromsosomes for fair comparison
k562.CTSSs.stand <- keepStandardChromosomes(k562.s.CTSSs,pruning.mode = "coarse")
k562.dhs<- keepStandardChromosomes(k562.dhs,pruning.mode = "coarse")
cumFrac <- cumulativeFractions(k562.dhs,k562.CTSSs.stand) 

ctss.cumfrac <- melt(cumFrac[[1]], id.var="distance")
ctss.cumfrac$method <- str_sub(ctss.cumfrac$variable,1,-2)

#Small naming change
levels(ctss.cumfrac$variable)[match("K562_N_10M",levels(ctss.cumfrac$variable))] <- "K562_10M_N"

ctss.cumfrac$variable[as.character(ctss.cumfrac$variable)=="K562_N_10M"] <- "K562_10M_N"
#Remove duplicated groCap
ctss.cumfrac <- ctss.cumfrac[as.character(ctss.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
ctss.cumfrac$variable <- factor(ctss.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p1 <- ggplot(ctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() +  labs(y="CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample") + scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed") + theme(legend.position="none")


p1.2 <- ggplot(ctss.cumfrac[ctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal)+ labs(y="Cumulative CTSS fraction at 200bp", x= "sample", fill="sample")


uctss.cumfrac <- melt(cumFrac[[2]], id.var="distance")
uctss.cumfrac$method <- str_sub(uctss.cumfrac$variable,1,-2)

#Small naming change
levels(uctss.cumfrac$variable)[match("K562_N_10M",levels(uctss.cumfrac$variable))] <- "K562_10M_N"
#Remove duplicated groCap
uctss.cumfrac <- uctss.cumfrac[as.character(uctss.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
uctss.cumfrac$variable <- factor(uctss.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p2 <- ggplot(uctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() + labs(y="unique CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")

p2.2 <- ggplot(uctss.cumfrac[uctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(y="Cumulative unique CTSS fraction at 200bp", x= "sample", fill="sample")


loci.cumfrac <- melt(cumFrac[[3]], id.var="distance")
loci.cumfrac$method <- str_sub(loci.cumfrac$variable,1,-2)
#Small naming change
levels(loci.cumfrac$variable)[match("K562_N_10M",levels(loci.cumfrac$variable))] <- "K562_10M_N"
#Remove duplicated groCap
loci.cumfrac <- loci.cumfrac[as.character(loci.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
loci.cumfrac$variable <- factor(loci.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p3 <- ggplot(loci.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw()  + labs(y="DHS to CTSS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")


p3.2 <- ggplot(loci.cumfrac[loci.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(y="Cumulative unique DHS fraction at 200bp", x= "sample", fill="sample")



pdf("./combined_plots/cumfrac.k562.repSub.DHS.pdf", height=20, width = 20)
grid.arrange(p1,p1.2,p2,p2.2,p3,p3.2 ,ncol=2)
dev.off()

saveRDS(list(ctss.cumfrac, uctss.cumfrac,loci.cumfrac),"cumfrac.k562.repSub.DHS.rds")

```



```{r}
#Remove non standard chromsosomes for fair comparison
k562.CTSSs.stand <- keepStandardChromosomes(k562.p.CTSSs,pruning.mode = "coarse")
k562.dhs<- keepStandardChromosomes(k562.dhs,pruning.mode = "coarse")
cumFrac <- cumulativeFractions(k562.dhs,k562.CTSSs.stand) 

ctss.cumfrac <- melt(cumFrac[[1]], id.var="distance")
ctss.cumfrac$method <- str_sub(ctss.cumfrac$variable,1,-2)

#Small naming change
levels(ctss.cumfrac$variable)[match("K562_N_10M",levels(ctss.cumfrac$variable))] <- "K562_10M_N"

ctss.cumfrac$variable[as.character(ctss.cumfrac$variable)=="K562_N_10M"] <- "K562_10M_N"
#Remove duplicated groCap
ctss.cumfrac <- ctss.cumfrac[as.character(ctss.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
ctss.cumfrac$variable <- factor(ctss.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p1 <- ggplot(ctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() +  labs(y="CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample") + scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed") + theme(legend.position="none")


p1.2 <- ggplot(ctss.cumfrac[ctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal)+ labs(y="Cumulative CTSS fraction at 200bp", x= "sample", fill="sample")


uctss.cumfrac <- melt(cumFrac[[2]], id.var="distance")
uctss.cumfrac$method <- str_sub(uctss.cumfrac$variable,1,-2)

#Small naming change
levels(uctss.cumfrac$variable)[match("K562_N_10M",levels(uctss.cumfrac$variable))] <- "K562_10M_N"
#Remove duplicated groCap
uctss.cumfrac <- uctss.cumfrac[as.character(uctss.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
uctss.cumfrac$variable <- factor(uctss.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p2 <- ggplot(uctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() + labs(y="unique CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")

p2.2 <- ggplot(uctss.cumfrac[uctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(y="Cumulative unique CTSS fraction at 200bp", x= "sample", fill="sample")


loci.cumfrac <- melt(cumFrac[[3]], id.var="distance")
loci.cumfrac$method <- str_sub(loci.cumfrac$variable,1,-2)
#Small naming change
levels(loci.cumfrac$variable)[match("K562_N_10M",levels(loci.cumfrac$variable))] <- "K562_10M_N"
#Remove duplicated groCap
loci.cumfrac <- loci.cumfrac[as.character(loci.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
loci.cumfrac$variable <- factor(loci.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p3 <- ggplot(loci.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw()  + labs(y="DHS to CTSS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")


p3.2 <- ggplot(loci.cumfrac[loci.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(y="Cumulative unique DHS fraction at 200bp", x= "sample", fill="sample")



pdf("./combined_plots/cumfrac.k562.poolSub.DHS.pdf", height=20, width = 20)
grid.arrange(p1,p1.2,p2,p2.2,p3,p3.2 ,ncol=2)
dev.off()


saveRDS(list(ctss.cumfrac, uctss.cumfrac,loci.cumfrac),"cumfrac.k562.poolSub.DHS.rds")

```




#K562 for rDHSs


```{r}
#Read in rDHS bed file form encode 
rdhs <- read.table("/maps/projects/ralab/people/pcr980/DeepCompare/Raw_data/rDHS_ENCFF619EJE.bed")
colnames(rdhs) <- c("chr","start","end")
rdhs <- GRanges(rdhs[,1:3])
rdhs$thick <- IRanges(start=start(rdhs)+((end(rdhs)-start(rdhs))/2))
```


```{r}
#Remove non standard chromsosomes for fair comparison
k562.CTSSs.stand <- keepStandardChromosomes(k562.s.CTSSs,pruning.mode = "coarse")
rdhs<- keepStandardChromosomes(rdhs,pruning.mode = "coarse")
cumFrac <- cumulativeFractions(rdhs,k562.CTSSs.stand) 

ctss.cumfrac <- melt(cumFrac[[1]], id.var="distance")
ctss.cumfrac$method <- str_sub(ctss.cumfrac$variable,1,-2)

#Small naming change
levels(ctss.cumfrac$variable)[match("K562_N_10M",levels(ctss.cumfrac$variable))] <- "K562_10M_N"

ctss.cumfrac$variable[as.character(ctss.cumfrac$variable)=="K562_N_10M"] <- "K562_10M_N"
#Remove duplicated groCap
ctss.cumfrac <- ctss.cumfrac[as.character(ctss.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
ctss.cumfrac$variable <- factor(ctss.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p1 <- ggplot(ctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() +  labs(y="CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample") + scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed") + theme(legend.position="none")


p1.2 <- ggplot(ctss.cumfrac[ctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal)+ labs(y="Cumulative CTSS fraction at 200bp", x= "sample", fill="sample")


uctss.cumfrac <- melt(cumFrac[[2]], id.var="distance")
uctss.cumfrac$method <- str_sub(uctss.cumfrac$variable,1,-2)

#Small naming change
levels(uctss.cumfrac$variable)[match("K562_N_10M",levels(uctss.cumfrac$variable))] <- "K562_10M_N"
#Remove duplicated groCap
uctss.cumfrac <- uctss.cumfrac[as.character(uctss.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
uctss.cumfrac$variable <- factor(uctss.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p2 <- ggplot(uctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() + labs(y="unique CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")

p2.2 <- ggplot(uctss.cumfrac[uctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(y="Cumulative unique CTSS fraction at 200bp", x= "sample", fill="sample")


loci.cumfrac <- melt(cumFrac[[3]], id.var="distance")
loci.cumfrac$method <- str_sub(loci.cumfrac$variable,1,-2)
#Small naming change
levels(loci.cumfrac$variable)[match("K562_N_10M",levels(loci.cumfrac$variable))] <- "K562_10M_N"
#Remove duplicated groCap
loci.cumfrac <- loci.cumfrac[as.character(loci.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
loci.cumfrac$variable <- factor(loci.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p3 <- ggplot(loci.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw()  + labs(y="DHS to CTSS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")


p3.2 <- ggplot(loci.cumfrac[loci.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(y="Cumulative unique DHS fraction at 200bp", x= "sample", fill="sample")



pdf("./combined_plots/cumfrac.k562.repSub.rDHS.pdf", height=20, width = 20)
grid.arrange(p1,p1.2,p2,p2.2,p3,p3.2 ,ncol=2)
dev.off()

saveRDS(list(ctss.cumfrac, uctss.cumfrac,loci.cumfrac),"cumfrac.k562.repSub.rDHS.rds")

```



```{r}
#Remove non standard chromsosomes for fair comparison
k562.CTSSs.stand <- keepStandardChromosomes(k562.p.CTSSs,pruning.mode = "coarse")
rdhs<- keepStandardChromosomes(rdhs,pruning.mode = "coarse")
cumFrac <- cumulativeFractions(rdhs,k562.CTSSs.stand) 

ctss.cumfrac <- melt(cumFrac[[1]], id.var="distance")
ctss.cumfrac$method <- str_sub(ctss.cumfrac$variable,1,-2)

#Small naming change
levels(ctss.cumfrac$variable)[match("K562_N_10M",levels(ctss.cumfrac$variable))] <- "K562_10M_N"

ctss.cumfrac$variable[as.character(ctss.cumfrac$variable)=="K562_N_10M"] <- "K562_10M_N"
#Remove duplicated groCap
ctss.cumfrac <- ctss.cumfrac[as.character(ctss.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
ctss.cumfrac$variable <- factor(ctss.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p1 <- ggplot(ctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() +  labs(y="CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample") + scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed") + theme(legend.position="none")


p1.2 <- ggplot(ctss.cumfrac[ctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal)+ labs(y="Cumulative CTSS fraction at 200bp", x= "sample", fill="sample")


uctss.cumfrac <- melt(cumFrac[[2]], id.var="distance")
uctss.cumfrac$method <- str_sub(uctss.cumfrac$variable,1,-2)

#Small naming change
levels(uctss.cumfrac$variable)[match("K562_N_10M",levels(uctss.cumfrac$variable))] <- "K562_10M_N"
#Remove duplicated groCap
uctss.cumfrac <- uctss.cumfrac[as.character(uctss.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
uctss.cumfrac$variable <- factor(uctss.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p2 <- ggplot(uctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() + labs(y="unique CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")

p2.2 <- ggplot(uctss.cumfrac[uctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(y="Cumulative unique CTSS fraction at 200bp", x= "sample", fill="sample")


loci.cumfrac <- melt(cumFrac[[3]], id.var="distance")
loci.cumfrac$method <- str_sub(loci.cumfrac$variable,1,-2)
#Small naming change
levels(loci.cumfrac$variable)[match("K562_N_10M",levels(loci.cumfrac$variable))] <- "K562_10M_N"
#Remove duplicated groCap
loci.cumfrac <- loci.cumfrac[as.character(loci.cumfrac$variable)!="K562_Cap_align",]
#Reorder samples as factors
loci.cumfrac$variable <- factor(loci.cumfrac$variable,levels=c( "K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6", "K562_N",
                                                                                       "K562_10M_N1", "K562_10M_N2","K562_10M_N3","K562_10M_N",
                                                                                       "K562_ProCap_pcr_1","K562_ProCap_pcr_2","K562_pcr_align","K562_groCap_1"))

p3 <- ggplot(loci.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw()  + labs(y="DHS to CTSS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=k.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")


p3.2 <- ggplot(loci.cumfrac[loci.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(y="Cumulative unique DHS fraction at 200bp", x= "sample", fill="sample")



pdf("./combined_plots/cumfrac.k562.poolSub.rDHS.pdf", height=20, width = 20)
grid.arrange(p1,p1.2,p2,p2.2,p3,p3.2 ,ncol=2)
dev.off()

saveRDS(list(ctss.cumfrac, uctss.cumfrac,loci.cumfrac),"cumfrac.k562.poolSub.rDHS.rds")
```




#Same flow for GM12878
```{r}
#Read in pre made CTSS objects
GM12878.s.CTSSs <- readRDS("repSub.combined.GM12878.CTSSs.rds")
GM12878.p.CTSSs <- readRDS("poolSub.combined.GM12878.CTSSs.rds")
```



```{r}
#Read in DHS bed file form encode 
GM12878.dhs <- read.table("../0.External_resources/E116-DNase.macs2.hg38.narrowPeak")
colnames(GM12878.dhs) <- c("chr","start","end")
GM12878.dhs <- GRanges(GM12878.dhs[,1:3])
GM12878.dhs$thick <- IRanges(start=start(GM12878.dhs)+((end(GM12878.dhs)-start(GM12878.dhs))/2))
```



```{r}
#Remove non standard chromsosomes for fair comparison
GM12878.CTSSs.stand <- keepStandardChromosomes(GM12878.s.CTSSs,pruning.mode = "coarse")
GM12878.dhs<- keepStandardChromosomes(GM12878.dhs,pruning.mode = "coarse")
cumFrac <- cumulativeFractions(GM12878.dhs,GM12878.CTSSs.stand[,colData(GM12878.CTSSs.stand)$main=="yes"]) 

ctss.cumfrac <- melt(cumFrac[[1]], id.var="distance")
ctss.cumfrac$method <- str_sub(ctss.cumfrac$variable,1,-2)


#Reorder samples as factors
ctss.cumfrac$variable <- factor(ctss.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))

p1 <- ggplot(ctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() +  labs(y="CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample") + scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed") + theme(legend.position="none")


p1.2 <- ggplot(ctss.cumfrac[ctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal)+ labs(y="Cumulative CTSS fraction at 200bp", x= "sample", fill="sample")


uctss.cumfrac <- melt(cumFrac[[2]], id.var="distance")
uctss.cumfrac$method <- str_sub(uctss.cumfrac$variable,1,-2)

#Reorder samples as factors
uctss.cumfrac$variable <- factor(uctss.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))
p2 <- ggplot(uctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() + labs(y="unique CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")

p2.2 <- ggplot(uctss.cumfrac[uctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal) + labs(y="Cumulative unique CTSS fraction at 200bp", x= "sample", fill="sample")


loci.cumfrac <- melt(cumFrac[[3]], id.var="distance")
loci.cumfrac$method <- str_sub(loci.cumfrac$variable,1,-2)

#Reorder samples as factors
loci.cumfrac$variable <- factor(loci.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))

p3 <- ggplot(loci.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw()  + labs(y="DHS to CTSS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")


p3.2 <- ggplot(loci.cumfrac[loci.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal) + labs(y="Cumulative unique DHS fraction at 200bp", x= "sample", fill="sample")

pdf("./combined_plots/cumfrac.GM12878.repSub.DHS.pdf", height=20, width = 20)
grid.arrange(p1,p1.2,p2,p2.2,p3,p3.2 ,ncol=2)
dev.off()

saveRDS(list(ctss.cumfrac, uctss.cumfrac,loci.cumfrac),"cumfrac.GM12878.repSub.DHS.rds")

```



```{r}
#Remove non standard chromsosomes for fair comparison
GM12878.CTSSs.stand <- keepStandardChromosomes(GM12878.p.CTSSs,pruning.mode = "coarse")
GM12878.dhs<- keepStandardChromosomes(GM12878.dhs,pruning.mode = "coarse")
cumFrac <- cumulativeFractions(GM12878.dhs,GM12878.CTSSs.stand[,colData(GM12878.CTSSs.stand)$main=="yes"]) 

ctss.cumfrac <- melt(cumFrac[[1]], id.var="distance")
ctss.cumfrac$method <- str_sub(ctss.cumfrac$variable,1,-2)


#Reorder samples as factors
ctss.cumfrac$variable <- factor(ctss.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))

p1 <- ggplot(ctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() +  labs(y="CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample") + scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed") + theme(legend.position="none")


p1.2 <- ggplot(ctss.cumfrac[ctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal)+ labs(y="Cumulative CTSS fraction at 200bp", x= "sample", fill="sample")


uctss.cumfrac <- melt(cumFrac[[2]], id.var="distance")
uctss.cumfrac$method <- str_sub(uctss.cumfrac$variable,1,-2)

#Reorder samples as factors
uctss.cumfrac$variable <- factor(uctss.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))
p2 <- ggplot(uctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() + labs(y="unique CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")

p2.2 <- ggplot(uctss.cumfrac[uctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal) + labs(y="Cumulative unique CTSS fraction at 200bp", x= "sample", fill="sample")


loci.cumfrac <- melt(cumFrac[[3]], id.var="distance")
loci.cumfrac$method <- str_sub(loci.cumfrac$variable,1,-2)

#Reorder samples as factors
loci.cumfrac$variable <- factor(loci.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))

p3 <- ggplot(loci.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw()  + labs(y="DHS to CTSS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")


p3.2 <- ggplot(loci.cumfrac[loci.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal) + labs(y="Cumulative unique DHS fraction at 200bp", x= "sample", fill="sample")


pdf("./combined_plots/cumfrac.GM12878.poolSub.DHS.pdf", height=20, width = 20)
grid.arrange(p1,p1.2,p2,p2.2,p3,p3.2 ,ncol=2)
dev.off()

saveRDS(list(ctss.cumfrac, uctss.cumfrac,loci.cumfrac),"cumfrac.GM12878.poolSub.DHS.rds")

```




#Gm12878 for rDHSs


```{r}
#Read in rDHS bed file form encode 
rdhs <- read.table("/maps/projects/ralab/people/pcr980/DeepCompare/Raw_data/rDHS_ENCFF619EJE.bed")
colnames(rdhs) <- c("chr","start","end")
rdhs <- GRanges(rdhs[,1:3])
rdhs$thick <- IRanges(start=start(rdhs)+((end(rdhs)-start(rdhs))/2))
```


```{r}
#Remove non standard chromsosomes for fair comparison
GM12878.CTSSs.stand <- keepStandardChromosomes(GM12878.s.CTSSs,pruning.mode = "coarse")
rdhs<- keepStandardChromosomes(rdhs,pruning.mode = "coarse")
cumFrac <- cumulativeFractions(rdhs,GM12878.CTSSs.stand[,colData(GM12878.CTSSs.stand)$main=="yes"]) 

ctss.cumfrac <- melt(cumFrac[[1]], id.var="distance")


#Reorder samples as factors
ctss.cumfrac$variable <- factor(ctss.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))

p1 <- ggplot(ctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() +  labs(y="CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample") + scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed") + theme(legend.position="none")


p1.2 <- ggplot(ctss.cumfrac[ctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal)+ labs(y="Cumulative CTSS fraction at 200bp", x= "sample", fill="sample")


uctss.cumfrac <- melt(cumFrac[[2]], id.var="distance")
uctss.cumfrac$method <- str_sub(uctss.cumfrac$variable,1,-2)

#Reorder samples as factors
uctss.cumfrac$variable <- factor(uctss.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))
p2 <- ggplot(uctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() + labs(y="unique CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")

p2.2 <- ggplot(uctss.cumfrac[uctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal) + labs(y="Cumulative unique CTSS fraction at 200bp", x= "sample", fill="sample")


loci.cumfrac <- melt(cumFrac[[3]], id.var="distance")
loci.cumfrac$method <- str_sub(loci.cumfrac$variable,1,-2)

#Reorder samples as factors
loci.cumfrac$variable <- factor(loci.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))

p3 <- ggplot(loci.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw()  + labs(y="DHS to CTSS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")


p3.2 <- ggplot(loci.cumfrac[loci.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal) + labs(y="Cumulative unique DHS fraction at 200bp", x= "sample", fill="sample")

pdf("./combined_plots/cumfrac.GM12878.repSub.rDHS.pdf", height=20, width = 20)
grid.arrange(p1,p1.2,p2,p2.2,p3,p3.2 ,ncol=2)
dev.off()

saveRDS(list(ctss.cumfrac, uctss.cumfrac,loci.cumfrac),"cumfrac.GM12878.repSub.rDHS.rds")

```



```{r}
#Remove non standard chromsosomes for fair comparison
GM12878.CTSSs.stand <- keepStandardChromosomes(GM12878.p.CTSSs,pruning.mode = "coarse")
rdhs<- keepStandardChromosomes(rdhs,pruning.mode = "coarse")
cumFrac <- cumulativeFractions(rdhs,GM12878.CTSSs.stand[,colData(GM12878.CTSSs.stand)$main=="yes"]) 
ctss.cumfrac <- melt(cumFrac[[1]], id.var="distance")


#Reorder samples as factors
ctss.cumfrac$variable <- factor(ctss.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))

p1 <- ggplot(ctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() +  labs(y="CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample") + scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed") + theme(legend.position="none")


p1.2 <- ggplot(ctss.cumfrac[ctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal)+ labs(y="Cumulative CTSS fraction at 200bp", x= "sample", fill="sample")


uctss.cumfrac <- melt(cumFrac[[2]], id.var="distance")
uctss.cumfrac$method <- str_sub(uctss.cumfrac$variable,1,-2)

#Reorder samples as factors
uctss.cumfrac$variable <- factor(uctss.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))
p2 <- ggplot(uctss.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw() + labs(y="unique CTSS to DHS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")

p2.2 <- ggplot(uctss.cumfrac[uctss.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal) + labs(y="Cumulative unique CTSS fraction at 200bp", x= "sample", fill="sample")


loci.cumfrac <- melt(cumFrac[[3]], id.var="distance")
loci.cumfrac$method <- str_sub(loci.cumfrac$variable,1,-2)

#Reorder samples as factors
loci.cumfrac$variable <- factor(loci.cumfrac$variable,levels=c( "GM12878_500K_C1","GM12878_500K_C2","GM12878_500K_C3","GM12878_500K_C",
                                                                "GM12878_500K_N1","GM12878_500K_N2","GM12878_500K_N3", "GM12878_500K_N",
                                                                "GM12878_1M_C1","GM12878_1M_C2","GM12878_1M_C3","GM12878_1M_C",
                                                                "GM12878_1M_N1","GM12878_1M_N2","GM12878_1M_N3", "GM12878_1M_N",
                                                                "GM12878_5M_N1","GM12878_5M_N2","GM12878_5M_N3", "GM12878_5M_N",
                                                                "GM12878_10M_N1","GM12878_10M_N2","GM12878_10M_N3", "GM12878_10M_N"))

p3 <- ggplot(loci.cumfrac,aes(distance,value, color=variable, group=variable)) + geom_line() + theme_bw()  + labs(y="DHS to CTSS cumulative fraction", x= "distance to DHSs center", color="sample")+ scale_color_manual(values=gm.full.pal) + geom_vline(xintercept=200,alpha=0.5,linetype="dashed")+ theme(legend.position="none")


p3.2 <- ggplot(loci.cumfrac[loci.cumfrac$distance==200,], aes(variable, value,fill=variable)) + geom_col() + theme_bw() + scale_fill_manual(values=gm.full.pal) + labs(y="Cumulative unique DHS fraction at 200bp", x= "sample", fill="sample")



pdf("./combined_plots/cumfrac.GM12878.poolSub.rDHS.pdf", height=20, width = 20)
grid.arrange(p1,p1.2,p2,p2.2,p3,p3.2 ,ncol=2)
dev.off()

saveRDS(list(ctss.cumfrac, uctss.cumfrac,loci.cumfrac),"cumfrac.GM12878.poolSub.rDHS.rds")

```


