---
title: "1.4.2.CTSSs.annFracs.Rmd"
output: html_document
date: "2024-02-29"
---


```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(CAGEfightR)

#CAGEfighR extensions
setwd("/home/mhf817")
sep <- .Platform$file.sep
cfr.extensions.dir <- "/home/mhf817/CAGEfightR_extensions"
source(paste(cfr.extensions.dir, "utils.R", sep = sep))
source(paste(cfr.extensions.dir, "support.R", sep = sep))
source(paste(cfr.extensions.dir, "cumulative.R", sep = sep))
source(paste(cfr.extensions.dir, "decompose.R", sep = sep))
source(paste(cfr.extensions.dir, "enhancers.R", sep = sep))
source(paste(cfr.extensions.dir, "noise.R", sep = sep))
source(paste(cfr.extensions.dir, "coverage.R", sep = sep))
source(paste(cfr.extensions.dir, "complexity.R", sep = sep))
source(paste(cfr.extensions.dir, "subsample.R", sep = sep))
source(paste(cfr.extensions.dir, "dispersion.R", sep = sep))


#Annotations
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

#Packages for plotting
library(CAGEfightR)
library(epistack)
library(BiocParallel)
library(dplyr)
library(reshape2)
library(limma)
library(ggplot2)
library(stringr)
library(gridExtra)

custom.col <- c("#FFDB6D", "#C4961A", "#F4EDCA", 
                "#D16103", "#C3D7A4", "#52854C", "#4E84C4", "#293352","grey")
                

custom.col <- c("#FFDB6D", "#C4961A", "#F4EDCA", 
                "#D16103", "#C3D7A4", "#52854C", "#4E84C4", "#293352","grey")


gm.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#DF613F","#DF5643","#DD4425","#92B9C9","#76A5B6","#004352","#29A957","#008E37","#007A30","#4F5D5C","#444E4C","#3D4138",
                     "#AC97C2","#977FB4","#7D62A3")
                     
gm.pooled.pal <- c("#FF8D00","#FF4425","#00439B","#009072","#878784","#7D62D0")

gm.full.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#FF8D00","#DF613F","#DF5643","#DD4425","#FF4425","#92B9C9","#76A5B6","#004352","#00439B","#29A957","#008E37","#007A30","#009072","#4F5D5C","#444E4C","#3D4138","#878784","#AC97C2","#977FB4","#7D62A3","#7D62D0")



k.full.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#FF8D00","#DF613F","#DF5643","#DD4425","#FF4425","#92B9C9","#76A5B6","#004352","#00439B","#29A957","#008E37","#007A30","#4F5D5C")


#Set working directory
setwd("/maps/projects/ralab/data/projects/nucleiCAGEproject/1.CTSSs")
```



```{r}
calc_anno_CTSS <- function(data, txModels) {
  
  data <- assignTxType(data,txModels = txModels)
  
  #Condiser all txTypes
  Types <- unique(rowData(data)$txType)
  
  # Initialize list to store total tags for each txType
  totalTags_list <- vector("list", length = length(Types))
  
  # Loop through each txType
  for (i in seq_along(Types)) {
    # Subset data based on current txType
    current_subset <- subset(data, txType %in% Types[i])
    # Calculate totalTags for current subset
    current_subset <- calcTotalTags(current_subset) %>% colData()
    totalTags_list[[i]] <- current_subset$totalTags
  }
  
  # Combine totalTags into a data frame
  ann_counts <- as.data.frame(do.call(cbind, totalTags_list))
  colnames(ann_counts) <- Types
  return(ann_counts)
}


calc_anno_uniqCTSS <- function(data, txModels) {
  
  data <- assignTxType(data,txModels = txModels)
  
  #Condiser all txTypes
  Types <- unique(rowData(data)$txType)
  
  # Initialize list to store total tags for each txType
  totalTags_list <- vector("list", length = length(Types))
  
  # Loop through each txType
  for (i in seq_along(Types)) {
    # Subset data based on current txType
    current_subset <- subset(data, txType %in% Types[i])
    # Calculate totalTags for current subset
    current_subset <- colSums(assay(current_subset)>0) 
    totalTags_list[[i]] <- current_subset
  }
  
  # Combine totalTags into a data frame
  ann_counts <- as.data.frame(do.call(cbind, totalTags_list))
  colnames(ann_counts) <- Types
  return(ann_counts)
}

```



```{r}
k562.s.CTSSs <- readRDS("repSub.combined.k562.CTSSs.rds")
k562.p.CTSSs <- readRDS("poolSub.combined.k562.CTSSs.rds")


GM12878.s.CTSSs <- readRDS("repSub.combined.GM12878.CTSSs.rds")
GM12878.p.CTSSs <- readRDS("poolSub.combined.GM12878.CTSSs.rds")


```





```{r}
#Quantify CTSS level annotations
gm12878.ann.counts <- calc_anno_CTSS(GM12878.s.CTSSs[,colData(GM12878.s.CTSSs)$main=="yes"],txModels = txdb)
gm12878.ann.fracs <- gm12878.ann.counts/colData(GM12878.s.CTSSs)$totalTags[colData(GM12878.s.CTSSs)$main=="yes"]

gm12878.ann.uniqcounts <- calc_anno_uniqCTSS(GM12878.s.CTSSs[,colData(GM12878.s.CTSSs)$main=="yes"],txModels = txdb)
gm12878.ann.uniqfracs <- gm12878.ann.uniqcounts/rowSums(gm12878.ann.uniqcounts)

gm12878.ann.counts.p <- calc_anno_CTSS(GM12878.p.CTSSs[,colData(GM12878.p.CTSSs)$main=="yes"],txModels = txdb)
gm12878.ann.fracs.p <- gm12878.ann.counts.p/colData(GM12878.p.CTSSs)$totalTags[colData(GM12878.p.CTSSs)$main=="yes"]

gm12878.ann.uniqcounts.p <- calc_anno_uniqCTSS(GM12878.p.CTSSs[,colData(GM12878.p.CTSSs)$main=="yes"],txModels = txdb)
gm12878.ann.uniqfracs.p <- gm12878.ann.uniqcounts.p/rowSums(gm12878.ann.uniqcounts.p)
```


```{r}
save(gm12878.ann.counts,gm12878.ann.fracs,gm12878.ann.uniqcounts,gm12878.ann.uniqfracs,gm12878.ann.counts.p,gm12878.ann.fracs.p,gm12878.ann.uniqcounts.p,gm12878.ann.uniqfracs.p, file="annFracs.gm12878.RData")
```



```{r}
gm12878.ann.fracs$sample <- row.names(gm12878.ann.fracs)


gm12878.ann.fracs.m <- melt(gm12878.ann.fracs)



#Plotting
p1 <- ggplot(gm12878.ann.fracs.m, aes(sample, value, fill=variable)) + geom_col() + coord_flip() +
  theme_bw() + scale_fill_manual(values=custom.col)

p2 <- ggplot(gm12878.ann.fracs, aes(intergenic, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(gm12878.ann.fracs), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=gm.full.pal)

p3 <- ggplot(gm12878.ann.fracs, aes(exon, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(gm12878.ann.fracs), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=gm.full.pal)

pdf("./combined_plots/annFracs.GM12878.repSub.pdf", height=20, width = 10)
grid.arrange(p1,p2,p3)
dev.off()


#
gm12878.ann.fracs.p$sample <- row.names(gm12878.ann.fracs.p)


gm12878.ann.fracs.p.m <- melt(gm12878.ann.fracs.p)



#Plotting
p1 <- ggplot(gm12878.ann.fracs.p.m, aes(sample, value, fill=variable)) + geom_col() + coord_flip() +
  theme_bw() + scale_fill_manual(values=custom.col)

p2 <- ggplot(gm12878.ann.fracs.p, aes(intergenic, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(gm12878.ann.fracs.p), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=gm.full.pal)

p3 <- ggplot(gm12878.ann.fracs.p, aes(exon, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(gm12878.ann.fracs.p), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=gm.full.pal)

pdf("./combined_plots/annFracs.GM12878.poolSub.pdf", height=20, width = 10)
grid.arrange(p1,p2,p3)
dev.off()

```



```{r}
#Unique CTSS fraction per annotation
gm12878.ann.uniqfracs$sample <- row.names(gm12878.ann.uniqfracs)



gm12878.ann.uniqfracs.m <- melt(gm12878.ann.uniqfracs)



#Plotting
p1 <- ggplot(gm12878.ann.uniqfracs.m, aes(sample, value, fill=variable)) + geom_col() + coord_flip() +
  theme_bw() + scale_fill_manual(values=custom.col)

p2 <- ggplot(gm12878.ann.uniqfracs, aes(intergenic, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(gm12878.ann.uniqfracs), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=gm.full.pal)

p3 <- ggplot(gm12878.ann.uniqfracs, aes(exon, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(gm12878.ann.uniqfracs), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=gm.full.pal)


pdf("./combined_plots/annuniqFracs.GM12878.repSub.pdf", height=20, width = 10)
grid.arrange(p1,p2,p3)
dev.off()




#
gm12878.ann.uniqfracs.p$sample <- row.names(gm12878.ann.uniqfracs.p)


gm12878.ann.uniqfracs.p.m <- melt(gm12878.ann.uniqfracs.p)



#Plotting
p1 <- ggplot(gm12878.ann.uniqfracs.p.m, aes(sample, value, fill=variable)) + geom_col() + coord_flip() +
  theme_bw() + scale_fill_manual(values=custom.col)

p2 <- ggplot(gm12878.ann.uniqfracs.p, aes(intergenic, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(gm12878.ann.uniqfracs.p), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=gm.full.pal)

p3 <- ggplot(gm12878.ann.uniqfracs.p, aes(exon, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(gm12878.ann.uniqfracs.p), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=gm.full.pal)

pdf("./combined_plots/annuniqFracs.GM12878.poolSub.pdf", height=20, width = 10)
grid.arrange(p1,p2,p3)
dev.off()






```












```{r}
#Quantify CTSS level annotations
k562.ann.counts <- calc_anno_CTSS(k562.s.CTSSs,txModels = txdb)
k562.ann.fracs <- k562.ann.counts/colData(k562.s.CTSSs)$totalTags

k562.ann.uniqcounts <- calc_anno_uniqCTSS(k562.s.CTSSs,txModels = txdb)
k562.ann.uniqfracs <- k562.ann.uniqcounts/rowSums(k562.ann.uniqcounts)

k562.ann.counts.p <- calc_anno_CTSS(k562.s.CTSSs,txModels = txdb)
k562.ann.fracs.p <- k562.ann.counts/colData(k562.s.CTSSs)$totalTags

k562.ann.uniqcounts.p <- calc_anno_uniqCTSS(k562.p.CTSSs,txModels = txdb)
k562.ann.uniqfracs.p <- k562.ann.uniqcounts.p/rowSums(k562.ann.uniqcounts.p)
```


```{r}
save(k562.ann.counts,k562.ann.fracs,k562.ann.uniqcounts,k562.ann.uniqfracs,k562.ann.counts,k562.ann.fracs.p,k562.ann.uniqcounts.p,k562.ann.uniqfracs.p, file="annFracs.k562.RData")
```


```{r}
k562.ann.fracs$sample <- row.names(k562.ann.fracs)
#Small naming change
k562.ann.fracs$sample[k562.ann.fracs$sample=="K562_N_10M"] <- "K562_10M_N"
k562.ann.fracs<- k562.ann.fracs[k562.ann.fracs$sample!="K562_Cap_align",]


k562.ann.fracs.m <- melt(k562.ann.fracs)





#Plotting
p1 <- ggplot(k562.ann.fracs.m, aes(sample, value, fill=variable)) + geom_col() + coord_flip() +
  theme_bw() + scale_fill_manual(values=custom.col)

p2 <- ggplot(k562.ann.fracs, aes(intergenic, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(k562.ann.fracs), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=k.full.pal)

p3 <- ggplot(k562.ann.fracs, aes(exon, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(k562.ann.fracs), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=k.full.pal)

pdf("./combined_plots/annFracs.k562.repSub.pdf", height=20, width = 10)
grid.arrange(p1,p2,p3)
dev.off()


#
k562.ann.fracs.p$sample <- row.names(k562.ann.fracs.p)

k562.ann.fracs.p$sample[k562.ann.fracs.p$sample=="K562_N_10M"] <- "K562_10M_N"
k562.ann.fracs.p<- k562.ann.fracs.p[k562.ann.fracs.p$sample!="K562_Cap_align",]


k562.ann.fracs.m <- melt(k562.ann.fracs)


k562.ann.fracs.p.m <- melt(k562.ann.fracs.p)



#Plotting
p1 <- ggplot(k562.ann.fracs.p.m, aes(sample, value, fill=variable)) + geom_col() + coord_flip() +
  theme_bw() + scale_fill_manual(values=custom.col)

p2 <- ggplot(k562.ann.fracs.p, aes(intergenic, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(k562.ann.fracs.p), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=k.full.pal)

p3 <- ggplot(k562.ann.fracs.p, aes(exon, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(k562.ann.fracs.p), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=k.full.pal)

pdf("./combined_plots/annFracs.k562.poolSub.pdf", height=20, width = 10)
grid.arrange(p1,p2,p3)
dev.off()

```



```{r}
#Unique CTSS fraction per annotation
k562.ann.uniqfracs$sample <- row.names(k562.ann.uniqfracs)

k562.ann.uniqfracs$sample[k562.ann.uniqfracs$sample=="K562_N_10M"] <- "K562_10M_N"
k562.ann.uniqfracs<- k562.ann.uniqfracs[k562.ann.uniqfracs$sample!="K562_Cap_align",]


k562.ann.uniqfracs.m <- melt(k562.ann.uniqfracs)



#Plotting
p1 <- ggplot(k562.ann.uniqfracs.m, aes(sample, value, fill=variable)) + geom_col() + coord_flip() +
  theme_bw() + scale_fill_manual(values=custom.col)

p2 <- ggplot(k562.ann.uniqfracs, aes(intergenic, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(k562.ann.uniqfracs), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=k.full.pal)

p3 <- ggplot(k562.ann.uniqfracs, aes(exon, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(k562.ann.uniqfracs), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=k.full.pal)


pdf("./combined_plots/annuniqFracs.k562.repSub.pdf", height=20, width = 10)
grid.arrange(p1,p2,p3)
dev.off()




#
k562.ann.uniqfracs.p$sample <- row.names(k562.ann.uniqfracs.p)

k562.ann.uniqfracs.p$sample[k562.ann.uniqfracs.p$sample=="K562_N_10M"] <- "K562_10M_N"
k562.ann.uniqfracs.p<- k562.ann.uniqfracs.p[k562.ann.uniqfracs.p$sample!="K562_Cap_align",]




k562.ann.uniqfracs.p.m <- melt(k562.ann.uniqfracs.p)



#Plotting
p1 <- ggplot(k562.ann.uniqfracs.p.m, aes(sample, value, fill=variable)) + geom_col() + coord_flip() +
  theme_bw() + scale_fill_manual(values=custom.col)

p2 <- ggplot(k562.ann.uniqfracs.p, aes(intergenic, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(k562.ann.uniqfracs.p), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=k.full.pal)

p3 <- ggplot(k562.ann.uniqfracs.p, aes(exon, intron, color=sample)) +
  geom_point(size=2) + theme_bw() + geom_text( label=rownames(k562.ann.uniqfracs.p), 
    check_overlap = F, size=3,nudge_y = 0.003) + 
  guides(color="none") + scale_color_manual(values=k.full.pal)

pdf("./combined_plots/annuniqFracs.k562.poolSub.pdf", height=20, width = 10)
grid.arrange(p1,p2,p3)
dev.off()

```



