---
title: '3.2.DL cumulative fractions vs expression'
output: html_document
date: "2024-02-13"
---

```{r}
library(CAGEfightR)

#CAGEfighR extensions
setwd("/home/mhf817")
sep <- .Platform$file.sep
cfr.extensions.dir <- "/home/mhf817/CAGEfightR_extensions"
source(paste(cfr.extensions.dir, "utils.R", sep = sep))
source(paste(cfr.extensions.dir, "support.R", sep = sep))
source(paste(cfr.extensions.dir, "cumulative.R", sep = sep))
source(paste(cfr.extensions.dir, "decompose.R", sep = sep))
source(paste(cfr.extensions.dir, "enhancers.R", sep = sep))
source(paste(cfr.extensions.dir, "noise.R", sep = sep))
source(paste(cfr.extensions.dir, "coverage.R", sep = sep))
source(paste(cfr.extensions.dir, "complexity.R", sep = sep))
source(paste(cfr.extensions.dir, "subsample.R", sep = sep))
source(paste(cfr.extensions.dir, "dispersion.R", sep = sep))


#Annotations
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

#Packages for plotting
library(CAGEfightR)
library(epistack)
library(BiocParallel)
library(dplyr)
library(reshape2)
library(limma)
library(ggplot2)
library(stringr)

custom.col <- c("#FFDB6D", "#C4961A", "#F4EDCA", 
                "#D16103", "#C3D7A4", "#52854C", "#4E84C4", "#293352","grey")


#Set working directory
setwd("/maps/projects/ralab/data/projects/nucleiCAGEproject/3.DivergentLoci/")


```



```{r}
#Load in previously called DLs 
k562.DLs.CTSS <- readRDS("subsampled.k562.DLs.CTSS.rds")
k562.DLs.TCs <- readRDS("subsampled.k562.DLs.TCs.rds")


GM12878.DLs.CTSS <- readRDS("IDpooled.subsampled.GM12878.DLs.CTSS.rds")
GM12878.DLs.TCs <- readRDS("IDpooled.subsampled.GM12878.DLs.TCs.rds")
```




```{r}


k562.DLs.df <- as.data.frame(k562.DLs.CTSS, row.names=NULL)
k562.DLs.summed = k562.DLs.df %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))
k562.DLs.summed$method <- str_sub(k562.DLs.summed$sample,1,-2)

k562.DLs.summed.sub = k562.DLs.df[k562.DLs.df$score>=2,] %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))
k562.DLs.summed.sub$method <- str_sub(k562.DLs.summed.sub$sample,1,-2)


k562.DLs.summed.sub.bidir = k562.DLs.df[k562.DLs.df$score>=2 & abs(k562.DLs.df$directionality)<=0.8,] %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))
k562.DLs.summed.sub.bidir$method <- str_sub(k562.DLs.summed.sub.bidir$sample,1,-2)

k562.DLs.summed.sub.bidir.olap = k562.DLs.df[k562.DLs.df$score>=2 & abs(k562.DLs.df$directionality)<=0.8& k562.DLs.df$dhs.olap>=1,] %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))
k562.DLs.summed.sub.bidir.olap$method <- str_sub(k562.DLs.summed.sub.bidir.olap$sample,1,-2)

pdf("./plots/k562.DLs.CTSS.cumulativeSums.pdf")
ggplot(k562.DLs.summed, aes(score,cumsum,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of all DLs")

ggplot(k562.DLs.summed, aes(score,cumsumCounts,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative counts of all DLs")


ggplot(k562.DLs.summed.sub, aes(score,cumsum,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of >=3 counts DLs")

ggplot(k562.DLs.summed.sub, aes(score,cumsumCounts,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative counts of >=3 counts DLs")


ggplot(k562.DLs.summed.sub.bidir, aes(score,cumsum,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative percentage of >=3 counts & bidirScore<0.8  DLs")

ggplot(k562.DLs.summed.sub.bidir, aes(score,cumsumCounts,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative counts of >=3 counts & bidirScore<0.8  DLs")



ggplot(k562.DLs.summed.sub.bidir.olap, aes(score,cumsum,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of >=3 counts & bidirScore<0.8 & DHS overlap  DLs")

ggplot(k562.DLs.summed.sub.bidir.olap, aes(score,cumsumCounts,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative counts of >=3 counts & bidirScore<0.8 & DHS overlap  DLs")

dev.off()
```




```{r}
k562.DLs.df <- as.data.frame(k562.DLs.TCs, row.names=NULL)
k562.DLs.summed = k562.DLs.df %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))
k562.DLs.summed$method <- str_sub(k562.DLs.summed$sample,1,-2)

k562.DLs.summed.sub = k562.DLs.df[k562.DLs.df$score>=2,] %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))
k562.DLs.summed.sub$method <- str_sub(k562.DLs.summed.sub$sample,1,-2)


k562.DLs.summed.sub.bidir = k562.DLs.df[k562.DLs.df$score>=2 & abs(k562.DLs.df$directionality)<=0.8,] %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))
k562.DLs.summed.sub.bidir$method <- str_sub(k562.DLs.summed.sub.bidir$sample,1,-2)

k562.DLs.summed.sub.bidir.olap = k562.DLs.df[k562.DLs.df$score>=2 & abs(k562.DLs.df$directionality)<=0.8& k562.DLs.df$dhs.olap>=1,] %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))
k562.DLs.summed.sub.bidir.olap$method <- str_sub(k562.DLs.summed.sub.bidir.olap$sample,1,-2)

pdf("./plots/k562.DLs.TCs.cumulativeSums.pdf")
ggplot(k562.DLs.summed, aes(score,cumsum,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of all DLs")

ggplot(k562.DLs.summed, aes(score,cumsumCounts,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative counts of all DLs")


ggplot(k562.DLs.summed.sub, aes(score,cumsum,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of >=3 counts DLs")

ggplot(k562.DLs.summed.sub, aes(score,cumsumCounts,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative counts of >=3 counts DLs")


ggplot(k562.DLs.summed.sub.bidir, aes(score,cumsum,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative percentage of >=3 counts & bidirScore<0.8  DLs")

ggplot(k562.DLs.summed.sub.bidir, aes(score,cumsumCounts,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative counts of >=3 counts & bidirScore<0.8  DLs")



ggplot(k562.DLs.summed.sub.bidir.olap, aes(score,cumsum,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of >=3 counts & bidirScore<0.8 & DHS overlap  DLs")

ggplot(k562.DLs.summed.sub.bidir.olap, aes(score,cumsumCounts,color=method)) +
  geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
  scale_color_manual(values=custom.col) + xlim(c(0,500)) + labs(title="cumulative counts of >=3 counts & bidirScore<0.8 & DHS overlap  DLs")

dev.off()
```





#GM12878
```{r}
GM12878.DLs.df <- as.data.frame(GM12878.DLs.CTSS, row.names=NULL)
GM12878.DLs.summed = GM12878.DLs.df %>% subset(!cell_count %in% c("ctrl","triptolide") ) %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))

GM12878.DLs.summed$cell_count <- str_extract(GM12878.DLs.summed$sample, "_(.*?)_")
GM12878.DLs.summed$cell_count <- gsub("_", "", GM12878.DLs.summed$cell_count )
GM12878.DLs.summed$cell_nuclei <- str_sub(GM12878.DLs.summed$sample,-2,-2)


GM12878.DLs.summed.sub = GM12878.DLs.df[GM12878.DLs.df$score>=2,] %>% subset(!cell_count %in% c("ctrl","triptolide") ) %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))

GM12878.DLs.summed.sub$cell_count <- str_extract(GM12878.DLs.summed.sub$sample, "_(.*?)_")
GM12878.DLs.summed.sub$cell_count <- gsub("_", "", GM12878.DLs.summed.sub$cell_count )
GM12878.DLs.summed.sub$cell_nuclei <- str_sub(GM12878.DLs.summed.sub$sample,-2,-2)

GM12878.DLs.summed.sub.bidir = GM12878.DLs.df[GM12878.DLs.df$score>=2 & abs(GM12878.DLs.df$directionality)<=0.8,] %>% subset(!cell_count %in% c("ctrl","triptolide") ) %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))

GM12878.DLs.summed.sub.bidir$cell_count <- str_extract(GM12878.DLs.summed.sub.bidir$sample, "_(.*?)_")
GM12878.DLs.summed.sub.bidir$cell_count <- gsub("_", "", GM12878.DLs.summed.sub.bidir$cell_count )
GM12878.DLs.summed.sub.bidir$cell_nuclei <- str_sub(GM12878.DLs.summed.sub.bidir$sample,-2,-2)


GM12878.DLs.summed.sub.bidir.olap = GM12878.DLs.df[GM12878.DLs.df$score>=2 & abs(GM12878.DLs.df$directionality)<=0.8& GM12878.DLs.df$dhs.olap>=1,] %>% subset(!cell_count %in% c("ctrl","triptolide") ) %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))

GM12878.DLs.summed.sub.bidir.olap$cell_count <- str_extract(GM12878.DLs.summed.sub.bidir.olap$sample, "_(.*?)_")
GM12878.DLs.summed.sub.bidir.olap$cell_count <- gsub("_", "", GM12878.DLs.summed.sub.bidir.olap$cell_count )
GM12878.DLs.summed.sub.bidir.olap$cell_nuclei <- str_sub(GM12878.DLs.summed.sub.bidir.olap$sample,-2,-2)




pdf("./plots/GM12878.DLs.CTSS.cumulativeSums.pdf")
ggplot(GM12878.DLs.summed, aes(score,cumsum,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of all DLs")

ggplot(GM12878.DLs.summed, aes(score,cumsumCounts,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative counts of all DLs")


ggplot(GM12878.DLs.summed.sub, aes(score,cumsum,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+  labs(title="cumulative percentage of >=3 counts DLs")

ggplot(GM12878.DLs.summed.sub, aes(score,cumsumCounts,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative counts of >=3 counts DLs")


ggplot(GM12878.DLs.summed.sub.bidir, aes(score,cumsum,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+  labs(title="cumulative percentage of >=3 counts & bidirScore<0.8  DLs")

ggplot(GM12878.DLs.summed.sub.bidir, aes(score,cumsumCounts,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative counts of >=3 counts & bidirScore<0.8  DLs")



ggplot(GM12878.DLs.summed.sub.bidir.olap, aes(score,cumsum,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of >=3 counts & bidirScore<0.8 & DHS overlap  DLs")

ggplot(GM12878.DLs.summed.sub.bidir.olap, aes(score,cumsumCounts,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative counts of >=3 counts & bidirScore<0.8 & DHS overlap  DLs")

dev.off()
```


```{r}
GM12878.DLs.df <- as.data.frame(GM12878.DLs.TCs, row.names=NULL)
GM12878.DLs.summed = GM12878.DLs.df %>% subset(!cell_count %in% c("ctrl","triptolide")) %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))

GM12878.DLs.summed$cell_count <- str_extract(GM12878.DLs.summed$sample, "_(.*?)_")
GM12878.DLs.summed$cell_count <- gsub("_", "", GM12878.DLs.summed$cell_count )
GM12878.DLs.summed$cell_nuclei <- str_sub(GM12878.DLs.summed$sample,-2,-2)


GM12878.DLs.summed.sub = GM12878.DLs.df[GM12878.DLs.df$score>=2,] %>% subset(!cell_count %in% c("ctrl","triptolide") ) %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))

GM12878.DLs.summed.sub$cell_count <- str_extract(GM12878.DLs.summed.sub$sample, "_(.*?)_")
GM12878.DLs.summed.sub$cell_count <- gsub("_", "", GM12878.DLs.summed.sub$cell_count )
GM12878.DLs.summed.sub$cell_nuclei <- str_sub(GM12878.DLs.summed.sub$sample,-2,-2)

GM12878.DLs.summed.sub.bidir = GM12878.DLs.df[GM12878.DLs.df$score>=2 & abs(GM12878.DLs.df$directionality)<=0.8,] %>% subset(!cell_count %in% c("ctrl","triptolide") ) %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))

GM12878.DLs.summed.sub.bidir$cell_count <- str_extract(GM12878.DLs.summed.sub.bidir$sample, "_(.*?)_")
GM12878.DLs.summed.sub.bidir$cell_count <- gsub("_", "", GM12878.DLs.summed.sub.bidir$cell_count )
GM12878.DLs.summed.sub.bidir$cell_nuclei <- str_sub(GM12878.DLs.summed.sub.bidir$sample,-2,-2)


GM12878.DLs.summed.sub.bidir.olap = GM12878.DLs.df[GM12878.DLs.df$score>=2 & abs(GM12878.DLs.df$directionality)<=0.8& GM12878.DLs.df$dhs.olap>=1,] %>% subset(!cell_count %in% c("ctrl","triptolide") ) %>% group_by(sample,txType) %>% count(score) %>%
         mutate(pct = n/sum(n)) %>% mutate(cumsum=cumsum(pct), cumsumCounts=cumsum(n))

GM12878.DLs.summed.sub.bidir.olap$cell_count <- str_extract(GM12878.DLs.summed.sub.bidir.olap$sample, "_(.*?)_")
GM12878.DLs.summed.sub.bidir.olap$cell_count <- gsub("_", "", GM12878.DLs.summed.sub.bidir.olap$cell_count )
GM12878.DLs.summed.sub.bidir.olap$cell_nuclei <- str_sub(GM12878.DLs.summed.sub.bidir.olap$sample,-2,-2)




pdf("./plots/GM12878.DLs.TCs.cumulativeSums.pdf")
ggplot(GM12878.DLs.summed, aes(score,cumsum,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of all DLs")

ggplot(GM12878.DLs.summed, aes(score,cumsumCounts,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative counts of all DLs")


ggplot(GM12878.DLs.summed.sub, aes(score,cumsum,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+  labs(title="cumulative percentage of >=3 counts DLs")

ggplot(GM12878.DLs.summed.sub, aes(score,cumsumCounts,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative counts of >=3 counts DLs")


ggplot(GM12878.DLs.summed.sub.bidir, aes(score,cumsum,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+  labs(title="cumulative percentage of >=3 counts & bidirScore<0.8  DLs")

ggplot(GM12878.DLs.summed.sub.bidir, aes(score,cumsumCounts,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative counts of >=3 counts & bidirScore<0.8  DLs")



ggplot(GM12878.DLs.summed.sub.bidir.olap, aes(score,cumsum,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType) + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative percentage of >=3 counts & bidirScore<0.8 & DHS overlap  DLs")

ggplot(GM12878.DLs.summed.sub.bidir.olap, aes(score,cumsumCounts,color=paste(cell_count,cell_nuclei))) +
    geom_line(aes(group=sample)) + facet_wrap(~txType, scales = "free_y") + theme_bw() +
    scale_color_manual(values=custom.col) + xlim(c(0,500))+ labs(title="cumulative counts of >=3 counts & bidirScore<0.8 & DHS overlap  DLs")

dev.off()
```






