---
title: "20250320_workflow_SHAPvisualization"
output: html_document
date: "2025-03-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## [0.0.] Load necessary packages
```{r}
base::library(GenomicRanges)
base::library(readr)
base::library(ggplot2)
base::library(dplyr)
base::library(ggplot2)
base::library(patchwork)
base::library(gridExtra)
base::library(CAGEfightR)
base::library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
```

## [0.2.] Helper function convert GRanges to DataFrame and set the rownames
```{r}
granges_to_df <- function(gr_obj, txdb) {
    df <- base::as.data.frame(gr_obj$gr)
    rownames(df) <- base::paste0(
        df$seqnames, ":",
        df$start, "-",
        df$end, ";",
        df$strand
      )
    gr_obj$df <- df
    return(gr_obj)
  }
```

## [0.3.] Helper function to compute average profiles
```{r}
compute_data_ave <- function(df_list) {
    data_ave <- base::data.frame(X = base::seq(-200, 200, length.out = 401))
    data_ave$SHAP <- base::colMeans(df_list$shap_value)
    data_ave$subtnorm <- base::colMeans(df_list$profile_subtnorm)
    data_ave$pos <- base::colMeans(df_list$profile_count_plus)
    data_ave$neg <- base::colMeans(df_list$profile_count_minus)
    return(data_ave)
  }
```

## [1.0.] Read in data
```{r}
K562_C <- base::readRDS(
    file = base::paste0(
      here::here("7.Model_development/"),
      "K562_C_endres_v2_shap-subtnorm-plus-minus-gr.rds"
    )
  )
K562_N <- base::readRDS(
  file = base::paste0(
    here::here("7.Model_development/"),
    "K562_N_endres_v2_shap-subtnorm-plus-minus-gr.rds"
  )
)
```

```{r}
K562_C$gr <- CAGEfightR::assignTxType(K562_C$gr, txdb)
K562_N$gr <- CAGEfightR::assignTxType(K562_N$gr, txdb)
```

```{r}
K562_C <- .GlobalEnv$granges_to_df(K562_C, txdb)
K562_N <- .GlobalEnv$granges_to_df(K562_N, txdb)
```

```{r}
data_ave_C <- .GlobalEnv$compute_data_ave(K562_C)
data_ave_N <- .GlobalEnv$compute_data_ave(K562_N)
```

```{r}
sample_name = "K562_C"
annotation = "all"
num_data = base::nrow(K562_C$df)

ggplot2::ggplot(
    data = data_ave_C,
    mapping = aes(
        x = X,
        y = SHAP
      )
    ) +
  geom_bar(
      stat = "identity",
      fill = "#7771AF",
      alpha = 0.7
    ) +
  labs(
      title = base::paste(
          "Average SHAP Values (", sample_name, ") -",
          annotation, "-", as.character(num_data), " rows"
        ),
      x = "Position (bp)",
      y = "SHAP Value"
    ) +
  theme_bw()
```

```{r}
sample_name = "K562_N"
annotation = "all"
num_data = base::nrow(K562_N$df)

ggplot2::ggplot(
    data = data_ave_N,
    mapping = aes(
        x = X,
        y = SHAP
      )
    ) +
  geom_bar(
      stat = "identity",
      fill = "#7771AF",
      alpha = 0.7
    ) +
  labs(
      title = base::paste(
          "Average SHAP Values (", sample_name, ") -",
          annotation, "-", as.character(num_data), " rows"
        ),
      x = "Position (bp)",
      y = "SHAP Value"
    ) +
  theme_bw()
```

```{r}
data_ave_C <- dplyr::mutate(
    .data = data_ave_C,
    sample = "cells"
  )
data_ave_N <- dplyr::mutate(
    .data = data_ave_C,
    sample = "nuclei"
  )

comb <- dplyr::bind_rows(data_ave_C,data_ave_N)
```

```{r}
sample_name = "K562_N"
annotation = "all"
num_data = base::nrow(K562_N$df)

ggplot2::ggplot(
    data = comb,
    mapping = aes(
        x = X,
        y = SHAP
      )
    ) +
  geom_bar(
      stat = "identity",
      fill = "#7771AF",
      colour = "#7771AF",
      alpha = 1
    ) +
  facet_wrap(
      facets = ~ sample
    ) +
  theme_bw() +
  theme(
      aspect.ratio = 1/2,
      panel.spacing = grid::unit(0.1,"lines")
    )
```

```{r}
ggplot2::ggsave(
    filename = base::paste0(
        here::here("7.Model_development/plots/"),
        base::format(base::Sys.Date(),"%Y%m%d"),
        "_ShapValues",
        "_CellsNuclei.pdf"
      ),
    plot = ggplot2::last_plot(),
    width = 8,
    height = 3,
    device = "pdf"
  )
```

```{r}
sample_name = "K562_N"
annotation = "all"
num_data = base::nrow(K562_N$df)

ggplot2::ggplot(
    data = comb,
    mapping = aes(
        x = X,
        y = subtnorm
      )
    ) +
  geom_bar(
      stat = "identity",
      fill = "#3E8E74",
      colour = "#3E8E74",
      alpha = 1
    ) +
  facet_wrap(
      facets = ~ sample
    ) +
  theme_bw() +
  theme(
      aspect.ratio = 1/2,
      panel.spacing = grid::unit(0.1,"lines")
    )
```

```{r}
ggplot2::ggsave(
    filename = base::paste0(
        here::here("7.Model_development/plots/"),
        base::format(base::Sys.Date(),"%Y%m%d"),
        "_SubtnormValues",
        "_CellsNuclei.pdf"
      ),
    plot = ggplot2::last_plot(),
    width = 8,
    height = 3,
    device = "pdf"
  )
```

```{r}
# Function to generate plots
generate_plots <- function(data_ave, sample_name, annotation, num_data) {

  n1 <- ggplot(data_ave, aes(x = X, y = SHAP)) +
    geom_bar(stat = "identity", fill = "#7771AF", alpha = 0.7) +
    labs(title = paste("Average SHAP Values (", sample_name, ") -",
                       annotation, "-", as.character(num_data), " rows"),
         x = "Position (bp)", y = "SHAP Value") +
    theme_minimal()

  n2 <- ggplot(data_ave, aes(x = X, y = subtnorm)) +
    geom_bar(stat = "identity", fill = "#3E8E74", alpha = 0.7) +
    labs(title = paste("Average Subtnorm Values (", sample_name, ") -",
                       annotation, "-", as.character(num_data), " rows"),
         x = "Position (bp)", y = "Subtnorm Value") +
    theme_minimal()

  n3 <- ggplot(data_ave, aes(x = X)) +
    geom_bar(aes(y = pos), stat = "identity", fill = "#264691", alpha = 0.7) +
    geom_bar(aes(y = -neg), stat = "identity", fill = "#DD553C", alpha = 0.7) +
    labs(title = paste("Average Profile Counts (", sample_name, ") - ",
                       annotation, " - ", as.character(num_data), " rows"),
         x = "Position (bp)", y = "Counts") +
    theme_minimal()

  # Ensure all plots are valid before saving
  if (!inherits(n1, "ggplot") || !inherits(n2, "ggplot") || !inherits(n3, "ggplot")) {
    message("One or more plots failed to generate. Skipping PDF saving for:",
            annotation)
    return(NULL)
  }
```


```{r}
# Save plots as PDF
  filename <- paste0("SHAP_Subtnorm_Profile_",
                     sample_name, "_",
                     annotation, ".pdf")

  if (file.exists(filename)) {
    file.remove(filename)
  }

  tryCatch({
    pdf(filename, width = 8, height = 12)
    grid.arrange(n1, n2, n3, ncol = 1)
    dev.off()
    message(paste("PDF saved as", filename))
  }, error = function(e) {
    message("Error while saving PDF for ", annotation, ": ", e$message)
  })

}
```


```{r}
generate_plots(data_ave_C, "K562_C", "all", nrow(K562_C$df))
generate_plots(data_ave_N, "K562_N", "all", nrow(K562_N$df))
```


```{r}
# Function to filter data frames based on annotations
filter_data_by_annotation <- function(data_list) {
  ref_df <- data_list$df
  annotation_categories <- unique(ref_df$txType)
  filtered_list <- list()

  for (ann in annotation_categories) {
    selected_rows <- rownames(ref_df[ref_df$txType == ann, ])
    filtered_list[[ann]] <- lapply(data_list, function(df) {
      if (is.data.frame(df)) {
        df[selected_rows, , drop = FALSE]
      }
    })
  }

  return(filtered_list)
}

K562_C_filtered_df <- filter_data_by_annotation(K562_C)
K562_N_filtered_df <- filter_data_by_annotation(K562_N)

for (ann in names(K562_C_filtered_df)) {
  df_list <- K562_C_filtered_df[[ann]]
  data_ave <- compute_data_ave(df_list)
  generate_plots(data_ave, "K562_C", ann, nrow(df_list$df))
}

for (ann in names(K562_N_filtered_df)) {
  df_list <- K562_N_filtered_df[[ann]]
  data_ave <- compute_data_ave(df_list)
  generate_plots(data_ave, "K562_N", ann, nrow(df_list$df))
}


```

