---
title: "9.1.Estimate_noise"
output: html_document
date: "2024-06-18"
---

Estimate noise levels across libraries

```{r}

library(CAGEfightR)
library(GenomicRanges)
library(rtracklayer)
library(GenomicFeatures)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)

setwd("/Users/fxc326/Documents/")
source("CAGEfightR_extensions/utils.R")
source("CAGEfightR_extensions/noise.R")
setwd("/Users/fxc326/Documents/nucCAGE/9.Noise")

```

```{r message=FALSE}
base::library(tidyverse)
```

```{r}

files <- c("HepG2.poolSub" = "../1.CTSSs/poolSub.HepG2.CTSSs.rmSingletons.rds",
           "A549.poolSub" = "../1.CTSSs/poolSub.A549.CTSSs.rmSingletons.rds",
           "HCT116.poolSub" = "../1.CTSSs/poolSub.HCT116.CTSSs.rmSingletons.rds",
           "K562.poolSub" = "../1.CTSSs/poolSub.combined.k562.CTSSs.rmSingletons.rds",
           "K562.repSub" = "../1.CTSSs/repSub.combined.k562.CTSSs.rmSingletons.rds",
           "GM12878.repSub" = "../1.CTSSs/repSub.combined.GM12878.CTSSs.rmSingletons.rds",
           "GM12878.poolSub" = "../1.CTSSs/poolSub.combined.GM12878.CTSSs.rmSingletons.rds")

CTSSs <- readRDS(files[1])

## uniquely mappable
map.gr.plus <- import.bed("uniquely_mappable/tracks/GRCh38_no_alt_analysis_set_GCA_000001405.15.73/GRCh38_no_alt_analysis_set_GCA_000001405.15.73.uniquely.mappable.plus.bed")
map.gr.minus <- import.bed("uniquely_mappable/tracks/GRCh38_no_alt_analysis_set_GCA_000001405.15.73/GRCh38_no_alt_analysis_set_GCA_000001405.15.73.uniquely.mappable.minus.bed")

seqlevels(map.gr.plus,pruning.mode="coarse") <- seqlevels(CTSSs)
seqlevels(map.gr.minus,pruning.mode="coarse") <- seqlevels(CTSSs)
seqinfo(map.gr.plus) <- seqinfo(map.gr.minus) <- seqinfo(CTSSs)
map.gr.plus <- trim(map.gr.plus)
map.gr.minus <- trim(map.gr.minus)

## mask
blacklist <- import.bed("../0.External_resources/ENCFF356LFX.bed")
hotspots <- import.bed("../0.External_resources/hotspots_merged_ext_300.bed")
exons <- flank(unlist(exonsBy(TxDb.Hsapiens.UCSC.hg38.knownGene,"tx")),50,both=TRUE)
mask <- reduce(c(blacklist,hotspots,exons))
seqlevels(mask,pruning.mode="coarse") <- seqlevels(CTSSs)
seqinfo(mask) <- seqinfo(CTSSs)
mask <- trim(mask)

for (n in names(files)) {
    CTSSs <- readRDS(files[n])
    divnoise <- estimateDivergentNoise(CTSSs, mask, map.gr.minus, map.gr.plus)
    divnoise
    write.csv(divnoise,paste0(n,".divnoise.csv"))
}

```

## [2.0.] Identify files
```{r}
fs <- base::list.files(
      path = here::here("9.Noise"),
      full.names = TRUE
    ) %>%
  stringr::str_subset("divnoise.csv")
```

## [2.1.] Read in & prepare datasets
```{r message=FALSE}
data <- purrr::map_dfr(
  .x = fs,
  .f = function(f){
    s <- stringr::str_extract(f,"poolSub|repSub")
    return(
      readr::read_delim(
            file = fs[1],
            delim = ",",
            col_names = TRUE
          ) %>%
        dplyr::rename(
            quantile = 1
          ) %>% 
        tidyr::pivot_longer(
            cols = !quantile,
            names_to = "variable",
            values_to = "value"
          ) %>%
        dplyr::mutate(
            subset = s
          )
        )
      }
    )
```

## [2.2.] Data wrangling
```{r}
reps <- base::c("pool","1","2","3")
amts <- base::c("500K","1M","5M","10M")

data.plot <- data %>%
  dplyr::filter(
    stringr::str_detect(
        variable, "trip|ctrl|Cap|align|50K|250K", negate = TRUE
      )
    ) %>%
  tidyr::separate_wider_delim(
      col = variable,
      names = base::c("cell","amount","type"),
      delim = "_"
    ) %>%
  tidyr::separate(
      col = type,
      sep = 1,
      into = base::c("source","rep"),
      convert = TRUE ## Creates NAs
    ) %>%
  dplyr::mutate(
    rep = dplyr::case_when(
        base::is.na(rep) ~ "pool",
        TRUE ~ base::as.character(rep)
      ),
    rep = base::factor(
        x = rep,
        levels = base::rev(reps),
        ordered = TRUE
      ),
    amount = base::factor(
        x = amount,
        levels = amts,
        ordered = TRUE
      ),
    source = base::factor(
        x = source,
        levels = base::c("C","N"),
        ordered = TRUE
      ),
    quantile = stringr::str_replace(quantile, "%", "") %>%
      base::as.double()
    )
```

## [2.3.] Test plotting
```{r}
ggplot2::ggplot(
      data = data.plot,
      mapping = aes(
        x = quantile, # base::log10(quantile),
        y = base::log2(value),
        color = rep
      )
    ) +
  geom_line(
      size = 1,
      alpha = 0.5
    ) +
  facet_wrap(
      facets = source ~ amount + subset,
      nrow = 2
    ) +
  theme_bw() +
  theme(
      aspect.ratio = 1,
      panel.spacing = grid::unit(0.1, "lines"),
      # legend.position = "none"
    )
```

## [2.4.] Subset for quantile=f(value>0) & quantile=f(max(value))
```{r}
data.plot %>%
  dplyr::filter(
      subset == "repSub" & value > 0
    ) %>% 
  dplyr::group_by(amount,source,rep) %>%
  dplyr::filter(
      value %in% base::c(base::min(value), base::max(value))
    ) %>% 
  dplyr::arrange(amount,source,rep)
```

# [3.] Estimate noise levels -------------------------

## [3.0.] Identify files
```{r}
files <- base::list.files(
      path = here::here("1.CTSSs"),
      full.names = TRUE
    ) %>%
  stringr::str_subset("CTSSs.rmSingletons.rds") %>%
  stringr::str_subset("GM12878|k562")

CTSSs <- base::readRDS(
    file = files[1]
  )
```

## [3.1.] Import uniquely mappable regions
```{r}
## uniquely mappable
map.gr.plus <- rtracklayer::import.bed(
  con = base::paste0(
      "uniquely_mappable/tracks/GRCh38_no_alt_analysis_set_GCA_000001405.15.73/",
      "GRCh38_no_alt_analysis_set_GCA_000001405.15.73.uniquely.mappable.plus.bed"
    )
  )
map.gr.minus <- rtracklayer::import.bed(
  con = base::paste0(
    "uniquely_mappable/tracks/GRCh38_no_alt_analysis_set_GCA_000001405.15.73/",
    "GRCh38_no_alt_analysis_set_GCA_000001405.15.73.uniquely.mappable.minus.bed"
    )
  )

seqlevels(map.gr.plus,pruning.mode="coarse") <- seqlevels(CTSSs)
seqlevels(map.gr.minus,pruning.mode="coarse") <- seqlevels(CTSSs)
seqinfo(map.gr.plus) <- seqinfo(map.gr.minus) <- seqinfo(CTSSs)
map.gr.plus <- trim(map.gr.plus)
map.gr.minus <- trim(map.gr.minus)

## mask
blacklist <- import.bed("../0.External_resources/ENCFF356LFX.bed")
hotspots <- import.bed("../0.External_resources/hotspots_merged_ext_300.bed")
exons <- flank(unlist(exonsBy(TxDb.Hsapiens.UCSC.hg38.knownGene,"tx")),50,both=TRUE)
mask <- reduce(c(blacklist,hotspots,exons))
seqlevels(mask,pruning.mode="coarse") <- seqlevels(CTSSs)
seqinfo(mask) <- seqinfo(CTSSs)
mask <- trim(mask)

for (n in names(files)) {
    CTSSs <- readRDS(files[n])
    divnoise <- estimateDivergentNoise(CTSSs, mask, map.gr.minus, map.gr.plus)
    divnoise
    write.csv(divnoise,paste0(n,".divnoise.csv"))
}

```