---
title: "4.1.TC.perSample"
output: html_document
date: "2024-03-05"
---


Calling of divergent locis and annotation of txType and overlaps with atac-seq regions

```{r}
library(CAGEfightR)

#CAGEfighR extensions
setwd("/home/mhf817")
sep <- .Platform$file.sep
cfr.extensions.dir <- "/home/mhf817/CAGEfightR_extensions"
source(paste(cfr.extensions.dir, "utils.R", sep = sep))
source(paste(cfr.extensions.dir, "support.R", sep = sep))
source(paste(cfr.extensions.dir, "cumulative.R", sep = sep))
source(paste(cfr.extensions.dir, "decompose.R", sep = sep))
source(paste(cfr.extensions.dir, "enhancers.R", sep = sep))
source(paste(cfr.extensions.dir, "noise.R", sep = sep))
source(paste(cfr.extensions.dir, "coverage.R", sep = sep))
source(paste(cfr.extensions.dir, "complexity.R", sep = sep))
source(paste(cfr.extensions.dir, "subsample.R", sep = sep))
source(paste(cfr.extensions.dir, "dispersion.R", sep = sep))


#Annotations
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene

#Packages for plotting
library(CAGEfightR)
library(epistack)
library(BiocParallel)
library(dplyr)
library(reshape2)
library(limma)
library(ggplot2)


custom.col <- c("#FFDB6D", "#C4961A", "#F4EDCA", 
                "#D16103", "#C3D7A4", "#52854C", "#4E84C4", "#293352","grey")


gm.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#DF613F","#DF5643","#DD4425","#92B9C9","#76A5B6","#004352","#29A957","#008E37","#007A30","#4F5D5C","#444E4C","#3D4138",
                     "#AC97C2","#977FB4","#7D62A3")
                     
gm.pooled.pal <- c("#FF8D00","#FF4425","#00439B","#009072","#878784","#7D62D0")

gm.full.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#FF8D00","#DF613F","#DF5643","#DD4425","#FF4425","#92B9C9","#76A5B6","#004352","#00439B","#29A957","#008E37","#007A30","#009072","#4F5D5C","#444E4C","#3D4138","#878784","#AC97C2","#977FB4","#7D62A3","#7D62D0")



k.full.pal <- c("#F5CE00", "#E2AA00", "#B68D00","#FF8D00","#DF613F","#DF5643","#DD4425","#FF4425","#4F5D5C","#92B9C9","#76A5B6","#004352","#00439B","#29A957","#008E37","#007A30")



#Set working directory
setwd("/maps/projects/ralab/data/projects/nucleiCAGEproject/4.Promoters/")


```


```{r}
#Function to create per sample clustering objects
perSampleTCs<- function(ctss, inputAssay="counts") {
  
  
  message(paste("Running TC calling for",colnames(ctss)))
  ## CalcPooled signal for sample and remove CTSSs with 0 score
  ctss <- calcPooled(ctss, inputAssay = inputAssay)
  ctss <- subset(ctss,score>0)
  
  #Call TCs for each sample
  object <- clusterUnidirectionally(ctss)
  object$sample <- colnames(ctss)
  ## Remove non-divergent cases
  object
}
```


#K562
```{r}
k562.s.CTSSs <- readRDS("../1.CTSSs/repSub.combined.k562.CTSSs.rds")

#Load in DHSs 
k562.dhs <- read.table("../0.External_resources/E123-DNase.macs2.hg38.narrowPeak")
colnames(k562.dhs) <- c("chr","start","end")
k562.dhs <- GRanges(k562.dhs[,1:3])
k562.dhs$thick <- IRanges(start=start(k562.dhs)+((end(k562.dhs)-start(k562.dhs))/2))
k562.dhs <- k562.dhs %>% swapRanges() %>% promoters(upstream=200, downstream=200) #Resize for equal width

```




```{r}
#Find any CTSS clusters across all samples. 
bpparam <- MulticoreParam(17)
k562.TCs <- bplapply(colnames(k562.s.CTSSs),function(x) perSampleTCs(k562.s.CTSSs[,x]), BPPARAM = bpparam)

olaps <- lapply(k562.TCs, function(x) countOverlaps(x,k562.dhs)) #Count number of overlaps with DHSs for annotations
k562.TCs <- suppressWarnings(lapply(k562.TCs, function(x) assignTxType(x,txModels=txdb))) #Assign txType as annotations for later

k562.TCs <- bplapply(1:length(k562.TCs),function(x) calcShape(k562.TCs[[x]], pooled=calcPooled(k562.s.CTSSs[,x])))
k562.TCs <- bplapply(1:length(k562.TCs),function(x) calcShape(object=k562.TCs[[x]], pooled=calcPooled(k562.s.CTSSs[,x]), shapeFunction=shapeEntropy, outputColumn="shapeEntropy"))

#Some formating 
k562.TCs <- GRangesList(k562.TCs) 
k562.TCs <- unlist(k562.TCs)
k562.TCs$dhs.olap <- unlist(olaps)

k562.TCs <- k562.TCs[k562.TCs$sample!="K562_Cap_align",]

k562.TCs$width <- width(k562.TCs)
```




PoolSub
```{r}
k562.p.CTSSs <- readRDS("../1.CTSSs/poolSub.combined.k562.CTSSs.rds")
```




```{r}
#Find any CTSS clusters across all samples. 
bpparam <- MulticoreParam(17)
k562.p.TCs <- bplapply(colnames(k562.p.CTSSs),function(x) perSampleTCs(k562.p.CTSSs[,x], inputAssay="TPM"), BPPARAM = bpparam)

olaps <- lapply(k562.p.TCs, function(x) countOverlaps(x,k562.dhs)) #Count number of overlaps with DHSs for annotations
k562.p.TCs <- suppressWarnings(lapply(k562.p.TCs, function(x) assignTxType(x,txModels=txdb))) #Assign txType as annotations for later

k562.p.TCs <- bplapply(1:length(k562.p.TCs),function(x) calcShape(k562.p.TCs[[x]], pooled=calcPooled(k562.p.CTSSs[,x])))
k562.p.TCs <- bplapply(1:length(k562.p.TCs),function(x) calcShape(object=k562.p.TCs[[x]], pooled=calcPooled(k562.p.CTSSs[,x]), shapeFunction=shapeEntropy, outputColumn="shapeEntropy"))

#Some formating 
k562.p.TCs <- GRangesList(k562.p.TCs) 
k562.p.TCs <- unlist(k562.p.TCs)
k562.p.TCs$dhs.olap <- unlist(olaps)

k562.p.TCs <- k562.p.TCs[k562.p.TCs$sample!="K562_Cap_align",]

k562.p.TCs$width <- width(k562.p.TCs)

k562.s.TCs$sample <- factor(k562.s.TCs$sample, levels=c("K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6","K562_N",
                                            "K562_10M_N1","K562_10M_N2","K562_10M_N3","K562_N_10M",
                                            "K562_groCap_1","K562_ProCap_pcr_2","K562_ProCap_pcr_1","K562_pcr_align"))


k562.p.TCs$sample <- factor(k562.p.TCs$sample, levels=c("K562_C1","K562_C2","K562_C3","K562_C","K562_N4","K562_N5","K562_N6","K562_N",
                                            "K562_10M_N1","K562_10M_N2","K562_10M_N3","K562_N_10M",
                                            "K562_groCap_1","K562_ProCap_pcr_2","K562_ProCap_pcr_1","K562_pcr_align"))
```




```{r}
saveRDS(k562.TCs, file="repSub.TCs.k562.rds")
saveRDS(k562.p.TCs, file="poolSub.TCs.k562.rds")
```



#Move this part to another script



```{r}
#Look at shapes 

k562.TCs %>% as.data.frame(row.names=NULL) %>%  subset(score>=100) %>%
  ggplot(aes(sample,fill=sample)) + geom_bar() + coord_flip() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(title="DLs detected score>=3") 

k562.TCs %>% as.data.frame(row.names=NULL) %>%  subset(score>=3) %>%
  ggplot(aes(txType,log10(score),fill=txType)) + geom_boxplot() + coord_flip() + theme_bw() + scale_fill_manual(values=custom.col) + labs(title="DLs detected score>=3") + facet_wrap(~sample) 

k562.TCs %>% as.data.frame(row.names=NULL) %>%  subset(dhs.olap>0) %>%
  ggplot(aes(sample,log10(score),fill=sample)) + geom_boxplot() + coord_flip() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(title="DLs detected score>=3") + facet_wrap(~txType) 

k562.TCs %>% as.data.frame(row.names=NULL) %>%  subset(dhs.olap>0 & width>1 & txType=="promoter") %>%
  ggplot(aes(shapeEntropy,fill=sample)) + geom_density() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(title="DLs detected score>=3") +facet_wrap(~sample)

k562.TCs %>% as.data.frame(row.names=NULL) %>%  subset(dhs.olap>0 & score>=10  & txType=="promoter") %>%
  ggplot(aes(log10(1+width),fill=sample)) + geom_density() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(title="DLs detected score>=3") +facet_wrap(~sample)


k562.TCs %>% as.data.frame(row.names=NULL) %>%  subset(dhs.olap>0 & score>=3  & txType=="promoter") %>%
  ggplot(aes(log10(1+width),fill=sample)) + geom_histogram() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(title="promoter width [bp]") +facet_wrap(~sample)



k562.TCs %>% as.data.frame(row.names=NULL) %>%  subset(dhs.olap>0 & score>=3  & txType=="promoter") %>%
  ggplot(aes(shapeEntropy,fill=sample)) + geom_histogram() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(title="promoter shapeEntropy") +facet_wrap(~sample) + xlim(-1,8)

k562.TCs %>% as.data.frame(row.names=NULL) %>%  subset(dhs.olap>0 & score>=3  & txType=="promoter") %>%
  ggplot(aes(IQR,fill=sample)) + geom_histogram() + theme_bw() + scale_fill_manual(values=k.full.pal) + labs(title="promoter 10-90IQR") +facet_wrap(~sample) + scale_x_log10()



```




