---
title: "4.2. Initiator analyses"
output: html_document
date: "2024-03-06"
---

## [0.] Prerequsites -------------------------

## [0.0.] Load necessary packages
```{r}
library(CAGEfightR)
library(PRIME)
library(BSgenome.Hsapiens.UCSC.hg38)
library(BiocParallel)
library(dplyr)
```


## [0.1.] Set working directory
```{r}
#setwd("/maps/projects/ralab/data/projects/nucCAGE_PRIME_paper/4.Promoters/")
```

# [1.] K562 replicate subsetted  -------------------------

## [1.0.] Read in data run classification and create output
```{r}
k562.TCs <- base::readRDS(
  file=paste0(here::here("4.Promoters/"),
  "repSub.TCs.k562.rds")
)
k562.TCs<- PRIME::initiatorScore(k562.TCs,Hsapiens)
base::saveRDS(k562.TCs, 
file=paste0(here::here("4.Promoters/"),
  "repSub.TCs.k562.rds"))
```


# [2.] K562 pool subsetted  -------------------------

## [2.0.] Read in data run classification and create output
```{r}
k562.p.TCs <- base::readRDS(file=paste0(here::here("4.Promoters/"),"poolSub.TCs.k562.rds"))
k562.p.TCs <- PRIME::initiatorScore(k562.p.TCs[,-8],Hsapiens)
base::saveRDS(k562.p.TCs, file=paste0(here::here("4.Promoters/"),"poolSub.TCs.k562.rds"))
```


# [3.] GM12878 replicate subsetted  -------------------------

## [3.0.] Read in data run classification and create output
```{r}
gm12878.TCs <- base::readRDS(file=paste0(here::here("4.Promoters/"),"repSub.TCs.GM12878.rds"))
gm12878.TCs <- PRIME::initiatorScore(gm12878.TCs,Hsapiens)
base::saveRDS(gm12878.TCs, file=paste0(here::here("4.Promoters/"),"repSub.TCs.GM12878.rds"))
```


# [4.] GM12878 pool subsetted  -------------------------

## [4.0.] Read in data run classification and create output
```{r}
gm12878.p.TCs <- base::readRDS(file=paste0(here::here("4.Promoters/"),"poolSub.TCs.GM12878.rds"))
gm12878.p.TCs <- PRIME::initiatorScore(gm12878.p.TCs,Hsapiens)
base::saveRDS(gm12878.p.TCs, file=paste0(here::here("4.Promoters/"),"poolSub.TCs.GM12878.rds"))
```