---
title: "4.4.promoterPlotting"
output: html_document
date: "2024-06-27"
---



## [0.] Prerequsites -------------------------

## [0.0.] Load necessary packages
```{r}
library(CAGEfightR)
library(dplyr)
library(ggplot2)
```


## [0.2.] Add custom color palettes
```{r}
custom.col <- base::c(
  "#FFDB6D","#C4961A","#F4EDCA", 
  "#D16103","#C3D7A4","#52854C",
  "#4E84C4","#293352","grey"
  )


gm.pal <- base::c(
  "#F5CE00","#E2AA00","#B68D00",
  "#DF613F","#DF5643","#DD4425",
  "#92B9C9","#76A5B6","#004352",
  "#29A957","#008E37","#007A30",
  "#4F5D5C","#444E4C","#3D4138",
  "#AC97C2","#977FB4","#7D62A3"
  )
                     
gm.pooled.pal <- base::c(
  "#FF8D00","#FF4425","#00439B",
  "#009072","#878784","#7D62D0"
  )

gm.full.pal <- base::c(
  "#F5CE00","#E2AA00","#B68D00",
  "#FF8D00","#DF613F","#DF5643",
  "#DD4425","#FF4425","#92B9C9",
  "#76A5B6","#004352","#00439B",
  "#29A957","#008E37","#007A30",
  "#009072","#4F5D5C","#444E4C",
  "#3D4138","#878784","#AC97C2",
  "#977FB4","#7D62A3","#7D62D0"
  )



k.full.pal <- base::c(
  "#F5CE00","#E2AA00","#B68D00",
  "#FF8D00","#DF613F","#DF5643",
  "#DD4425","#FF4425","#4F5D5C",
  "#92B9C9","#76A5B6","#004352",
  "#00439B","#29A957","#008E37",
  "#007A30"
  )
```

## [0.3.] Set working directory
```{r}
base::setwd("/maps/projects/ralab/data/projects/nucleiCAGEproject/4.Promoters/")
```


# [1.] Plotting K562 replicate subsetted metrics  

## [1.0.] Read in TC and gene level metrics
```{r}
base::load("./repSub.k562.GeneLevel.RData")
k562.TCs <- base::readRDS("repSub.TCs.k562.rds")
```


## [1.1.] Plot number and activity metrics of TCs
```{r}
#Number and activity
k562.TCs %>% 
  BiocGenerics::as.data.frame(row.names=NULL) %>%
  BiocGenerics::subset(score>=10) %>%
  ggplot2::ggplot(aes(x=sample,fill=sample)) +
  geom_bar() +
  coord_flip() +
  scale_fill_manual(values=k.full.pal) +
  labs(title="TCs detected score>=10") +
  facet_wrap(~txType) +
  theme(
      aspect.ratio = 1,
      legend.title = element_blank(),
      legend.justification = base::c(1,0),
      legend.background = element_rect(
          fill = "grey95"
        ),
      legend.text = element_text(size = 8),
      legend.key.size = grid::unit(0.9, "lines")
    )

ggplot2::ggsave(
  filename="./plots/nTCs.10Score.pdf",
  plot=last_plot(),
  width=15,
  height=15)

k562.TCs %>% 
  BiocGenerics::as.data.frame(row.names=NULL) %>%
  BiocGenerics::subset(dhs.olap>0) %>%
  ggplot2::ggplot(aes(x=sample,fill=sample)) +
  geom_bar() +
  coord_flip() +
  scale_fill_manual(values=k.full.pal) +
  labs(title="TCs detected overlapping DHSs") +
  facet_wrap(~txType) +
  theme(
      aspect.ratio = 1,
      legend.title = element_blank(),
      legend.justification = base::c(1,0),
      legend.background = element_rect(
          fill = "grey95"
        ),
      legend.text = element_text(size = 8),
      legend.key.size = grid::unit(0.9, "lines")
    )

ggplot2::ggsave(
  filename="./plots/nTCs.dhs.pdf",
  plot=last_plot(),
  width=15,
  height=15)


k562.TCs %>% 
  BiocGenerics::as.data.frame(row.names=NULL) %>%
  BiocGenerics::subset(score>=10) %>%
  ggplot2::ggplot(aes(x=sample,y=log10(score),fill=sample)) +
  geom_boxplot() +
  coord_flip() +
  scale_fill_manual(values=k.full.pal) +
  labs(title="TCs expression with >=10 score") +
  facet_wrap(~txType) +
  theme(
      aspect.ratio = 1,
      legend.title = element_blank(),
      legend.justification = base::c(1,0),
      legend.background = element_rect(
          fill = "grey95"
        ),
      legend.text = element_text(size = 8),
      legend.key.size = grid::unit(0.9, "lines")
    )

ggplot2::ggsave(
  filename="./plots/TCs.expression.10Score.pdf",
  plot=last_plot(),
  width=15,
  height=15)

k562.TCs %>% 
  BiocGenerics::as.data.frame(row.names=NULL) %>%
  BiocGenerics::subset(dhs.olap>0) %>%
  ggplot2::ggplot(aes(x=sample,y=log10(score),fill=sample)) +
  geom_boxplot() +
  coord_flip() +
  scale_fill_manual(values=k.full.pal) +
  labs(title="TCs expression overlapping DHSs") +
  facet_wrap(~txType) +
  theme(
      aspect.ratio = 1,
      legend.title = element_blank(),
      legend.justification = base::c(1,0),
      legend.background = element_rect(
          fill = "grey95"
        ),
      legend.text = element_text(size = 8),
      legend.key.size = grid::unit(0.9, "lines")
    )

ggplot2::ggsave(
  filename="./plots/TCs.expression.dhs.pdf",
  plot=last_plot(),
  width=15,
  height=15)


```


## [1.2.] Plot shape metrics of TCs
```{r}

k562.TCs %>% 
  BiocGenerics::as.data.frame(row.names=NULL) %>%
  BiocGenerics::subset(score>=10 & txType=="promoter") %>%
  ggplot2::ggplot(aes(x=shapeEntropy,fill=sample)) + 
  geom_density() +
  scale_fill_manual(values=k.full.pal) + 
  labs(title="promoter shapeEntropy") +
  facet_wrap(~sample) +
  xlim(0,7.5) + 
  theme(
    aspect.ratio = 1,
    legend.title = element_blank(),
    legend.justification = base::c(1,0),
    legend.background = element_rect(
        fill = "grey95"
      ),
    legend.text = element_text(size = 8),
    legend.key.size = grid::unit(0.9, "lines")
  )

ggplot2::ggsave(
  filename="./plots/promoter.shapeEntopy.10Score.pdf",
  plot=last_plot(),
  width=15,
  height=15)


k562.TCs %>% 
  BiocGenerics::as.data.frame(row.names=NULL) %>%
  BiocGenerics::subset(score>=10 & txType=="promoter") %>%
  ggplot2::ggplot(aes(log10(1+IQR),fill=sample)) + 
  geom_density() + 
  scale_fill_manual(values=k.full.pal) + 
  labs(title="promoter 10-90IQR") +
  facet_wrap(~sample) +
  xlim(0,2.5) + 
  theme(
    aspect.ratio = 1,
    legend.title = element_blank(),
    legend.justification = base::c(1,0),
    legend.background = element_rect(
        fill = "grey95"
      ),
    legend.text = element_text(size = 8),
    legend.key.size = grid::unit(0.9, "lines")
  )


ggplot2::ggsave(
  filename="./plots/promoter.IQR.10Score.pdf",
  plot=last_plot(),
  width=15,
  height=15)

```




## [1.2.] Plot initator metrics of TCs
```{r}

k562.TCs %>% 
  BiocGenerics::as.data.frame(row.names=NULL) %>%
  BiocGenerics::subset(score>=10 & txType=="promoter") %>%
  ggplot2::ggplot(aes(sample, log10(score),fill=sample)) +
  scale_fill_manual(values=k.full.pal) +
  geom_boxplot() +
  labs(title="promoter summit initiator expression >=10 counts") +
  facet_wrap(~INR,ncol=1) + 
  coord_flip()
  xlim(0,2.5) + 
  theme(
    aspect.ratio = 1,
    legend.title = element_blank(),
    legend.justification = base::c(1,0),
    legend.background = element_rect(
        fill = "grey95"
      ),
    legend.text = element_text(size = 8),
    legend.key.size = grid::unit(0.9, "lines")
  )
  
ggplot2::ggsave(
  filename="./plots/promoter.initatorExpression.10Score.pdf",
  plot=last_plot(),
  width=10,
  height=15)


k562.TCs %>% 
  BiocGenerics::as.data.frame(row.names=NULL) %>%
  BiocGenerics::subset(score>=10 & txType=="promoter") %>%
  group_by(sample, INR) %>% 
  summarise(count = n()) %>% 
  mutate(perc = count/sum(count)) %>%
  ggplot2::ggplot(aes(x = INR, y = perc*100, fill = sample)) + 
  geom_col(position="dodge") + 
  scale_fill_manual(values=k.full.pal) +
  labs(title="promoter summit initiator >=10 counts") + 
  coord_flip()+ 
  theme(
    aspect.ratio = 1,
    legend.title = element_blank(),
    legend.justification = base::c(1,0),
    legend.background = element_rect(
        fill = "grey95"
      ),
    legend.text = element_text(size = 8),
    legend.key.size = grid::unit(0.9, "lines")
  )

ggplot2::ggsave(
  filename="./plots/promoter.nInitiators.10Score.pdf",
  plot=last_plot(),
  width=10,
  height=10)

```


## [1.4.] Plot gene level metrics°
```{r}
k562.cor.df$sample <- k562.cor.df$samp
k562.comb.expr %>%
  base::subset(TPM>0 & gene_counts>0) %>%
  ggplot2::ggplot(aes(gene_counts,TPM,color=sample,group=sample))+
  geom_point(size=0.5) +
  geom_text(data=k562.cor.df,
            aes(label=paste0("r=",round(correlation,3)),x=2.5e+5,y=2.5e+5,group=sample),
            inherit.aes = FALSE,size=4) +
  facet_wrap(~sample) + 
  scale_x_log10() +
  scale_y_log10() +
  scale_color_manual(values=k.full.pal) +
    theme(
    aspect.ratio = 1,
    legend.title = element_blank(),
    legend.justification = base::c(1,0),
    legend.background = element_rect(
        fill = "grey95"
      ),
    legend.text = element_text(size = 8),
    legend.key.size = grid::unit(0.9, "lines")
  ) 

ggplot2::ggsave(
  filename="./plots/geneExpression.pdf",
  plot=last_plot(),
  width=20,
  height=20)
  
```

